### ISSUE TITLE
Endless rendering if series is not wrap in a list by line charts

### ISSUE THREAD

**Issue by Azd325** [chartist-js/chartist#103]
I discovered today if I create a line chart and i didn't wrap a single series in square brackets. It starts to render endless and the page get unusable.

```
  data = {
    labels: labels,
    series: series
  };
```

to 

```
  data = {
    labels: labels,
    series: [series]
  };
```

**Comment by gionkunz** [comment]
This is because chartist always expect an array of series (except the pie chart). Not sure if we should introduce code to make the api more fault tolerant but landing in a infinite loop is certainly not very nice. Lets keep this open as a bug.

**Comment by nfriedly** [comment]
I noticed a similar issue when passing in an empty data set, and I tracked it down to this loop: https://github.com/gionkunz/chartist-js/blob/6891c5644d4b4aa8818dca88897829734e306702/src/scripts/core.js#L447

Adding a counter and make it stop after 1000 iterations fixed it for me. 

(I was going to send a PR, but I'm apparently blocked from contributing to WTFPL-licensed projects due to my employment agreement/corporate legal bullshit. But, if someone else wanted to implement the same idea, that wouldn't be breaking any rules ;)

**Comment by gionkunz** [comment]
Reconsidering this I'm actually against code bloat just to handle invalid usage of the API and provide graceful handling of these cases. If the API isn't documented well enough that's an other issue. I'll close this issue and if we have more issues like this in the future we should increase the quality of the documentation or simplify the API instead of producing fault tolerance code bloat.
