### ISSUE TITLE
Keep aspect ratio when scaling

### ISSUE THREAD

**Issue by ivandokov** [chartist-js/chartist#1054]
Hello everyone.
I am making my charts responsive and I'd like to keep the aspect ratio of the svg.
CSS Tricks suggests `viewBox` and `preserveAspectRatio` attributes but those are not included.
I'd like to have 100% width and the height to be auto.
Any ideas how to tackle this?

**Comment by gionkunz** [comment]
viewBox currently makes not much sense for Chartist, since we'd like to preserve certain elements from being scaled automatically. The responsive container classes are exactly what you're looking for:

```html
<div class="chart ct-golden-section"></div>
```

The ct-golden-section class is keeping your container in a 1:1.618 ratio for example. There are many different ratios you can choose from. Check this documentation: http://gionkunz.github.io/chartist-js/getting-started.html#creating-a-chart-using-aspect-ratios

**Comment by kleinfreund** [comment]
@gionkunz I don’t see how this answers the question. Without a viewBox attribute, setting `width: 100%` on the svg element won’t actually scale the image.
