### ISSUE TITLE
How to reduce the Y axis grid lines

### ISSUE THREAD

**Issue by MattWCarp** [chartist-js/chartist#1168]
I'm looking to graph up to 86,000 values on a line chart.  

Chartist is automatically determining the horizontal lines.   Is there a way to control that?

 
<img width="639" alt="Screen Shot 2019-04-21 at 12 06 14 PM" src="https://user-images.githubusercontent.com/2839757/56472550-e46a7a00-642d-11e9-9714-b879e17fd1cc.png">

HTML 

`<div class="ct-chart1" id="WaterTemp-chart"></div>`

JS

`    var ChartOptions_Temp = {
      width:  600,
      height: 200,
      showPoint: false
    };
    
   $.getJSON("/history?cid=5&key=temp", function(json) {
             new Chartist.Line('.ct-chart1', json, ChartOptions_Temp);
          }, 10000);`
`

**Comment by duchuy** [comment]
1. you can increase the scaleMinSpace in option
`` var ChartOptions_Temp = {
width: 600,
height: 200,
showPoint: false,
 axisY: {    
  scaleMinSpace: 100 // default is 20px
}
};`

2. you can override labelInterpolationFnc() to decide only display the ticks if the value match certain values

``` var ChartOptions_Temp = {
width: 600,
height: 200,
showPoint: false,
 axisY: {    
   labelInterpolationFnc: function labelInterpolationFnc(value, index) {
      if(value % 100 === 0) return value;
      return null;
   }
};`
`

**Comment by plainOldNerd** [comment]
Although this is 5 months after the original posting, I'm hoping it helps someone in future (if not the original poster).

I'm assuming you're referring to the thick grey "horizontal" lines. You can get rid of them entirely, if you wish, by adding
```
options = {
   axisX: {
      showGrid: false
   }
}
```

This might seem counter-intuitive (that it's axisX and not axisY) but actually these are dotted vertical line segments that are squished together because you have so many (eighty six thousand) data points in a small space, hence appearing to be horizontal lines.

For this reason, you cannot control the spacing between them, but you can get rid of them.

Hope this helps.
