### ISSUE TITLE
Overlapping colors  in Point Chart

### ISSUE THREAD

**Issue by ElVasquito** [chartist-js/chartist#1208]
Happy New Year to all!
Thanks for the Chartist lib, I've been fiddling with it for the last few days, it had its learning curve, but I mostly got it showing what I need :)
My question or issue is, for a chart like this:

[
![Chart](https://user-images.githubusercontent.com/55246603/71639232-f99cd700-2c51-11ea-9286-7e4e7493423b.jpg)
](url)

Is it possible for the overlapping dots to 'sum up' their color as they combine? As it is, the yellow ones (series 3) are hiding everything under them so you can't really tell if there are points behind.
Maybe there's a function, or some CSS I missed or overlooked in the documentation, sorry if this is the case!
TIA

**Comment by Arantiryo** [comment]
Hello @ElVasquito  👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).

Please let me know if the issue is still relevant to you so we can further investigate it!

**Comment by ElVasquito** [comment]
Thank you for the update @Arantiryo. I will check it as time permits and reopen if this is still somewhat an issue. Closing.
