### ISSUE TITLE
State variables not showing up in React chartist

### ISSUE THREAD

**Issue by AnonJon** [chartist-js/chartist#1210]
Im currently trying to set the data with information from an API call. If i hard code numbers into the fields it works ex.
`let data = {
    labels: ["12am", "3pm", "6pm", "9pm", "12pm", "3am", "6am", "9am"],
    series: [[4, 5]]
  };`

 but as soon as I switch it out for data thats saved to the state from the api call nothing shows up

`let data = {
    labels: ["12am", "3pm", "6pm", "9pm", "12pm", "3am", "6am", "9am"],
    series: [[labels1, labels1]]
  };`

ive console.log'd both the state and also the data.series which responds with the correct info, but the chart itself doesn't show anything. Is it because the page loads and then tries to load the data but doesn't refresh?

**Comment by Arantiryo** [comment]
Hello @jongregis 👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).

Please let me know if the issue is still relevant to you so we can further investigate it!
