### ISSUE TITLE
How to add a label with no series value

### ISSUE THREAD

**Issue by macsupport** [chartist-js/chartist#1214]
Sorry if this is confusing. 
I am generating a line chart of values over time generated from user input of each time and series value. It is a chart of blood glucose values during the day. There are 8 times and values available. I also need to add an additional time value which will not have a series value ( so the y value is not connected to the line, only the time shows). Basically I need to add a start time label for the chart  before the actual chart line starts (start time = 1 hour before the chart line starts).
Is it possible to do this in some way?

In this screenshot, I would want a time value at least 1 hour before the 04:00 start of the chart.

<img width="754" alt="Screen Shot 2020-01-27 at 2 45 02 PM" src="https://user-images.githubusercontent.com/624656/73220598-ab290e00-4113-11ea-8bc9-33ff9efe65b3.png">

**Comment by ismith78** [comment]
Hi,

If I'm understanding your question, you have a set of data that starts at 04:00 but you want the X axis to start at 03:00.

As you haven't supplied any sample code, I'm going to assume that you are using an AutoScaleAxis on your X axis. And if that is also true then that, unfortunately, is the problem as the autoscale uses the supplied data and fits within those ranges.

In order to have more control over the X axis, you need to be using a FixedScaleAxis and then define the ticks to start and end where you want. So if you want to start at 03:00 and end at 08:00, then you will need to define an array of 6 ticks. As these ticks are numbers you will need to use the epoch value for the date and time you need.

Have a look at the definition of FixedScaleAxis in the API documentation at https://gionkunz.github.io/chartist-js/api-documentation.html.
