### ISSUE TITLE
Zooming in with X axis as time with FixedScaleAxis shows out of bounds data on the edge on bar charts

### ISSUE THREAD

**Issue by ismith78** [chartist-js/chartist#1215]
I have a set of data that I need the ability to zoom in and out of the chart. For this reason I have to use a FixedScaleAxis for the X axis in order to manage the resizing of the start and end points.

This works fine with a line graph. However when using a bar graph what I observe is that there is a "collection" of bars to either side of the graph. Looking at each SVG element I can see that if the data from the series is before the low value then a bar is rendered with x1 and x2 of 50. If the data is after the high then another bar is rendered with x1 and x2 with the value corresponding to the edge of the chart, such as 189.

In my test code at https://jsbin.com/ruxogim/edit?html,css,js,output tapping on the zoom in button should be displaying the data from midnight 14th December 2019 to midnight 16th December 2019, which is two values. The two values are displayed but with a pillar of 16 to the far left and a pillar of 12 to the far right, representing the highest value either side of the range.

**Comment by Arantiryo** [comment]
Hello @ismith78 👋

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).

Please let me know if the issue is still relevant to you so we can further investigate it!
