### ISSUE TITLE
showArea and showLine parameters are ignored if the data isn't in ascending order and axisX.type is Chartist.AutoScaleAxis,

### ISSUE THREAD

**Issue by wujekbogdan** [chartist-js/chartist#1216]
I've just found (after I spend a lot of time on debugging) that the line and the area are drawn only if the data is in ascending order, otherwise `showLine: true` and `showArea: true` paramterers are ignored and the chart is drawn as they were both set to `false`.

I'm not sure is it a bug or is it an intended behaviour. If it's not a bug then it should be documented or, at least, some warning should show up in the console.

**Update**

I've also found it's related to `axisX.type` settings. It happens when `axisX.type === Chartist.AutoScaleAxis`. Otherwise, the line and the area is fine.

**Comment by gionkunz** [comment]
Hi, can you please post an example to reproduce this? Thanks!

**Comment by wujekbogdan** [comment]
Sure. Here you go: https://codepen.io/wujekbogdan/pen/JjdEROb

**Comment by gionkunz** [comment]
Hi, I just checked and this is somewhat an expected behaviour, although it should probably be documented better (like many things in chartist). There's a feature on the line interpolation to render holes if there are holes in the data (you can check the example page for that). This feature sort of relies on the data being sorted on the X-axis in a ascending order. 

If you don't need the fillHoles feature, you can disable it in the interpolation function. Here's an example: https://codepen.io/gionkunz/pen/ZEGLKLL

**Comment by wujekbogdan** [comment]
Got it. Thank you.
