### ISSUE TITLE
Bug with curves between big up/down steps

### ISSUE THREAD

**Issue by maslowivan** [chartist-js/chartist#123]
![Image of Yaktocat](http://habrastorage.org/files/7d2/4ce/085/7d24ce08592d436482696da7ba162798.png)

Code for example which will be demonstate curve-bug:

``` javascript
new Chartist.Line('.ct-chart', {
  "series": [[0, 0, 0, 0, 0, 1, 0]], "labels": ["2014-12-20T18:26:25", "2014-12-21T18:26:25", "2014-12-22T18:26:25", "2014-12-23T18:26:25", "2014-12-24T18:26:25", "2014-12-25T18:26:25", "2014-12-26T18:26:25"]
});
```

**Comment by gionkunz** [comment]
Hey there. This is a catmull rome spine artifact and happens when there are huge data gaps. We are already considering other interpolation functions in issue #92 . I'll close your issue in favor of the other one as we already have a discussion there. Please track any progress or contribute there. Cheers
