### ISSUE TITLE
More than 4 lines in a chart not possible?

### ISSUE THREAD

**Issue by ruudmanager3** [chartist-js/chartist#124]
Hi, absolutely love chartist capabilities!

I have been playing around with it and somehow it won't display more than 4 lines in a line chart. 
Thought I might have made a mistake, but if I modify the examples on documentation-site, it is also not possible.

Example from the documentation site - the fifth line won't be drawn:
new Chartist.Line('.ct-chart', {
  labels: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
  series: [
    [12, 9, 7, 8, 5],
    [2, 1, 3.5, 7, 3],
    [1, 3, 4, 5, 6],
     [10, 30, 40, 5, 6],
     [12, 31, 4, 5, 6]
  ]
});

Is this a limitation of chartist or I am indeed missing someting?

Regards,
Mark

**Comment by gionkunz** [comment]
Hey there. Thanks for the nice words :-) The lines are drawn by Chartist but unfortunately Chartist only knows 4 colours by default. You can either use the Sass version of Chartist and just override the colours array by adding more colours, or you can just add your colours in CSS http://jsbin.com/teyugo/1/edit?css,js,output .

However, I think we should add the default style with a default color so that it does not confuse people to not see the series at all. I'll leave this issue open until we've changed the default styling.

**Comment by ruudmanager3** [comment]
Thanks a lot for pointing that out! It helps me for now; I will dive into Sass at a later time :-)

Keep up the good work! Really off-the-charts :-)

**Comment by gionkunz** [comment]
Thanks! :-) There is still much to do in order to fully use today's browser power but I hope we'll get there ;-)

**Comment by ilanbiala** [comment]
I would think having 6-8 default colors would be much better, because the scheme would look more cohesive, and requires less configuration out of the box.

**Comment by vincurekf** [comment]
Hello Chartists,
i just came across this issue and found one solution.

For example for Pie chart you need to:
~~Add `seriesColors = [],` after [this line](https://github.com/gionkunz/chartist-js/blob/develop/dist/chartist.js#L2446)~~

Then you need to edit this part:
[line 2538](https://github.com/gionkunz/chartist-js/blob/develop/dist/chartist.js#L2538)

``` javascript
if(options.donut === true) {
path.attr({
'style': 'stroke-width: ' + (+options.donutWidth) + 'px'
});
}
```

and instead paste this:

``` javascript
// get color from this.data, if undefined, generate random number
// you can place your custom default color here ;) or leave the generator
var color = typeof this.data.colors !== 'undefined' ? this.data.colors[i] : '#'+(Math.random().toFixed(6).toString(16)).slice(2);
// if we are rendering donut, set the stroke color, otherwise set fill
if(options.donut === true) {
  path.attr({
    'style': 'stroke-width: ' + (+options.donutWidth) + 'px;' + 'stroke: ' + color
  });
}else{
  path.attr({
    'style': 'fill: ' + color
  });
}
```

It is pretty obvious :) 
After these two steps you can pass colors to your chart in datasets, like below:

``` javascript
var chartistData = {
        labels: [Mon, Tue, Due, West],
        series: [20, 40, 2, 1],
        colors: ['#ef9922', '#55ef22', 'red', 'blue']
      };

new Chartist.Pie('.ct-chart', chartistData, {
      donut: true,
      donutWidth: 40,
      startAngle: 360,
      total: 0,
      showLabel: true
    });
```

Hope that this was helpful for someone.

**Comment by gionkunz** [comment]
@vincurekf, I appreciate you're sharing your monkey patch but I'd like to state here that I don't support this solution. Chartist was created with a clean separation of concerns as one of it's core principles and colors should be specified in CSS. In case of dynamic colors you should use the `draw`event.

**Comment by gionkunz** [comment]
Some example of using the draw event to create dynamic appearance:
http://jsbin.com/pemute/1/edit?js,output
http://jsbin.com/xusinu/1/edit?css,js,output

**Comment by vincurekf** [comment]
@gionkunz oh, i dindn't think of the draw event. That is reasonable solution for dynamic color change without changing the core code. But i still miss the option to set the colors within the chart dataset.
Anyway, thanks for your advice :)

**Comment by Founts** [comment]
@gionkunz love the Sass implementation and therefore the separation of presentation and content. Confused though - I updated chartistsettings.scss to increase the series size to 5 items (added 'e') and added another color. I compiled and Sass produced an error:

<pre>Syntax error: List index is 5 but list is only 4 items long for `nth'
        on line 130 of source/css/vendor/chartist/chartist.scss, in `ct-chart'
        from line 141 of source/css/vendor/chartist/chartist.scss
        from line 62 of source/css/style-supp.scss</pre>

My guess is I wasn't supposed to do this. Is it best to add a color series outside of the Sass settings file?

**Comment by gionkunz** [comment]
Hey guys I've finally took the initiative and created more colors for Chartist :-) I'm not a color expert but I hope that I've created a nicely balanced color palette of 14 colors. I've respected the old colors as far as possible. The only differences to the old color set is that the 4th color is now an orange instead of brown. 

I hope you like them:
![chartist-series-default-colors](https://cloud.githubusercontent.com/assets/2203704/5788938/38098668-9e55-11e4-9dc1-535ec7049dd5.png)

An in a line Chart:
![chartist-14-colours](https://cloud.githubusercontent.com/assets/2203704/5788946/8be5ca3a-9e55-11e4-9a6c-cffc0d07314d.png)

@Founts , you did exactly the right thing. Are you sure you added the same amount of series names as colours? I think if you added too many series names and forgot to add all the colours you'll run into this issue. For the new 14 default colours I only extended these Sass lists (I wasn't using maps because were still issues in LibSass with maps). Check the commit: aad8067

**Comment by ilanbiala** [comment]
@gionkunz YES!!!!! Thank you!!

**Comment by Founts** [comment]
@gionkunz Regarding compile issue: I ended up removing the !default to get Sass to compile. Any idea why this fixed my problem?

<pre>$ct-series-names: (a, b, c, d, e, f, g) !default;
$ct-series-colors: (#45130E #D74F42 #FF7567 #453A1A #F4C63D #FFE8A3 #3B382E);</pre>

**Comment by gionkunz** [comment]
I'm really not sure why this is happening @Founts and I can't reproduce it locally. Are you using Ruby Sass or Node Sass / Lib Sass? Which version are you using?

**Comment by Founts** [comment]
@gionkunz Thanks for the response and checking on it. I'm running Ruby Sass 3.3.6 Maptastic. I wouldn't sweat this issue any further. (checked for latest) Guess my version is quite old!

**Comment by Founts** [comment]
@gionkunz Regarding the colors, they are good. I'm not sure if you are aware however, there are some accessibility issues for those with color vision deficiency (Deuteranopia, etc.). Color accessibility can be handled two different ways: either with project defaults or by developer implementation. 
For default, select colors with more contrast or avoid placing colors with similar contrast next to each other. 
For developer implementation, you could recommend that dev/designers use patterns (dashes, stripes, etc.). Not sure this project has patterns for all charts just yet though.

**Comment by gsklee** [comment]
@gionkunz Just curious - I found that `.ct-chart .ct-series.ct-series-e .ct-line` works while `.ct-series.ct-series-e .ct-line` and simply `.ct-line` won't. Is this normal when styling SVG with CSS?

**Comment by gionkunz** [comment]
@gsklee no this is normal in CSS as the specificity is lower with one class selector less. I think the Chartist selector specificity is too high anyway and as we're using ct- prefixes anyway we could get rid of a lot of those so I created #207

**Comment by gionkunz** [comment]
@Founts sorry your last message slipped through my radar somehow. I'd love to take accessibility into account as much as possible and I'm aware that the red, orange, yellow part is not easy to distinguish even for perfectly sighted people. However, because I didn't wanted people who used the default colors to have issues with the updated version, I've kept the sequence like this.
