### ISSUE TITLE
Plot data values along the X-Axis and provide real XY graphing

### ISSUE THREAD

**Issue by abauzac** [chartist-js/chartist#127]
Hello and thanks a lot for this awesome lib :)

I have a suggestion for an enhancement (or maybe I haven't found how to do it?) :
How about keeping proportions on the X Axis ?
On the Y axis for example, the values are splitted, let's say, in 8 values with the same step. 
It would be huge to have the same behaviour on the X axis. The various points would not be on the grid, but it would keep proportions. It would make sense for mathematical charts :)

I hope I'm clear enough :
Here is an illustration to explain 
![chartist](https://cloud.githubusercontent.com/assets/3852008/5603281/53ea7f18-937e-11e4-857b-2b09cb5d6ada.PNG)

BR

**Comment by gionkunz** [comment]
Hey there :-) Currently Chartist does not support plot style graphs. In fact, Chartist is a 2D graph library but the X-Axis is step based rather than projected. There is a similar request for Date based data series #116 . Your issue is similar in that the X-Axis would no longer be step based but show a scale and the values are projected (same as with dates). 

I've renamed your issue to target a wider audience and we can track the need for this feature here. On the date feature there are already some votes. 

In the current version of Chartist there is no way to implement plotting along the X-Axis as the whole system is step based.

**Comment by mathiasrw** [comment]
+1 vote for implementing this

**Comment by Remco75** [comment]
+1, seems really a must have...

**Comment by wehlutyk** [comment]
+1 to this!

**Comment by gionkunz** [comment]
This can now be done in 0.9.0. Check the documentation: http://gionkunz.github.io/chartist-js/getting-started.html#switching-axis-type

**Comment by mathiasrw** [comment]
:+1:
