### ISSUE TITLE
yuicompressor-maven-plugin

### ISSUE THREAD

**Issue by vicmosin** [chartist-js/chartist#132]
I try to minify the source code with that plugin and it always fails.. Even if I use the minified version and try to minify my own js file (which uses chartist methods) it fails...
Here are logs:

`...chartist.js:line 926:column 19:missing name after . operator
          constr.super = superProto;`
`[ERROR] ...chartist.js:line 2111:column 26:missing name after . operator
          Chartist.Line.super.constructor.call(this,`
`[ERROR] ...chartist.js:line 2112:column 14:syntax error
            query,`
`[ERROR] ...chartist.js:line 2113:column 13:syntax error
            data,`
`[ERROR] ...chartist.js:line 2114:column 18:syntax error
            Chartist.extend({}, defaultOptions, options),`
`[ERROR] ...chartist.js:line 2115:column 26:syntax error
            responsiveOptions);`
`[ERROR] ...chartist.js:line 2357:column 25:missing name after . operator
          Chartist.Bar.super.constructor.call(this,`
`[ERROR] ...chartist.js:line 2358:column 14:syntax error
            query,`
`[ERROR] ...chartist.js:line 2359:column 13:syntax error
            data,`
`[ERROR] ...chartist.js:line 2360:column 18:syntax error
            Chartist.extend({}, defaultOptions, options),`
`[ERROR] ...chartist.js:line 2361:column 26:syntax error
            responsiveOptions);`
`[ERROR] ...chartist.js:line 2656:column 25:missing name after . operator
          Chartist.Pie.super.constructor.call(this,`
`[ERROR] ...chartist.js:line 2657:column 14:syntax error
            query,`
`[ERROR] ...chartist.js:line 2658:column 13:syntax error
            data,`
`[ERROR] ...chartist.js:line 2659:column 18:syntax error
            Chartist.extend({}, defaultOptions, options),`
`[ERROR] ...chartist.js:line 2660:column 26:syntax error
            responsiveOptions);`
`[ERROR] ...chartist.js:line 1:column 0:Compilation produced 16 syntax errors.`

**Comment by vicmosin** [comment]
I know that Chartist is modern-browser oriented and this error mostly for old ones, but anyway the solution will be the following: change all `bla-bla.super` occurencies to `bla-bla['super']`

**Comment by gionkunz** [comment]
You're right. Chartist is for browsers that support ECMAScript 5+ and even though `super` is a reserved words / keyword, the specification states clearly for object accessors ( `MemberExpression . IdentifierName`) an `IdentifierName` can be used and not an `Identifier`. An `IdentifierName` is almost any Unicode 3 expression and doesn't care about reserved words. Reserved words are only forbidden to use in `Identifiers` which as per the specification is an `IdentifierName` **but not** `ReservedWord`. 

Anyway, I'd say the issue is with YUI Compressor not supporting ECMA Script 5.1 properly and should be fixed there. I know they had a few GitHub issues around reserved words like `private` and `class` but they always just reply with that those words are reserved, which if you ask me is not correct. They should fix this.

Also I'd not recommend using YUI Compressor as they moved away from using it themselves ( http://www.yuiblog.com/blog/2012/10/16/state-of-yui-compressor/ ) years ago :smile: 

I personally prefer UglifyJS or even Google Closure Compiler over YUICompressor (I was using YUI Compressor with some Ruby Projects) and I'd recommend you to switch to uglifyjs-maven-plugin.

Cheers
Gion

**Comment by gionkunz** [comment]
@nKognito I'm closing this issue for now. If you still think we should fix something on our end feel free to re-open and start an other discussion.
