### ISSUE TITLE
Script issue : SCRIPT1003: Expected ':'

### ISSUE THREAD

**Issue by qualityking** [chartist-js/chartist#143]
Hi Folks, 
am new to this chart, trying to do a kinda "Hello World" but facing issue running it. 
getting error, 'Chartist' is undefined, when checked in IE debugger found error like 

SCRIPT1003: Expected ':' 
chartist.js, line 552 character 17

digging into the code, it is taking me to the next line where a TODO is written 
// TODO: Remove in next major release

Please take a look

**Comment by gionkunz** [comment]
Hey there. Chartist.js requires IE9+

**Comment by qualityking** [comment]
Hey Gionkunz, 
thanks for the reply, 
I am using IE10 currently on windows 7...  (surprising but the fact is examples on the website is working fine on the same browser) 
I followed the instruction given, may be if you have any sample example (of a vanilla chart) to confirm everything is at place and configured properly would help! 

Not sure what is wrong but looks like something is massy with the why I am trying to run the example or something is wrong with chartist.js itself. can you please confirm I am using .js from the dist folder and not using Bower for installation.

**Comment by gionkunz** [comment]
Okay, probably your issue is not related to the error you see on the console. If Chartist is undefined then it's probably due to the loading order. Where do you include the Chartist script and where do you execute your code that creates a chart? You need to make sure that the code that loads Chartist is higher up in the DOM than the script that creates the Chart. Can you share your code? It's quite hard to find the issue like this.

**Comment by gionkunz** [comment]
I'm closing this issue. If you experience further problems please comment or open a new issue. Cheers
Gion
