### ISSUE TITLE
Resizing Chartist svg height

### ISSUE THREAD

**Issue by exhauster** [chartist-js/chartist#153]
Hi!

We are currently working on a feature that allows the user to rotate the labels 45 degrees. For this purpose, we would need to resize the height of the whole svg element, which is currently set to 100% (multiline labels are cutted of). So we need more space at the bottom for our labels? Is there a nice way to achieve this? i have tried various ways, but i don't want to lose responsiveness of the 100% height property. 

Thanks! George

**Comment by gionkunz** [comment]
Hey there! You can use regular CSS3 transforms to displace and rotate the labels. Labels are spans inside of foreign objects where the foreign object width and height will determine if the text in the span will wrap or not. By default Chartist sets the foreign object width to the gap between two grid lines on the X-Axis. You can modify that behavior by using the draw events of Chartist. The following example sets the foreign object width to something fixed and lengthy so that the containing spans don't wrap. Don't forget to set the `transform-origin` property so that the rotation is made at the start of the label. Also include a `margin-bottom` on your chart so you can reserve the space used by the transformed labels:

http://jsbin.com/zabewa/1/edit?html,css,js,output

**Comment by exhauster** [comment]
Thank you very, very much! I will try that today. At the moment, i used the transform attribute of the foreign object to rotate the labels - is it better to use CSS3 transforms?

**Comment by gionkunz** [comment]
Hey there. As browser support should not be an issue for you (IE9+) I'd use CSS3 transforms as they separate your Chart information from the appearance. You could easily use the same chart again and just display it differently using CSS. SVG transforms have a bit better browser support I guess (old android, FF and Chrome) but you'll put them onto your SVG which kind of breaks the separation of concerns.

**Comment by gionkunz** [comment]
I'm closing this issue for now. Please re-open if you have any other concerns.

**Comment by GPMMM** [comment]
Hey there,

I have this example, http://jsbin.com/ratenisabe/1/edit?html,css,js,output .
It works well in chrome, but not in Firefox and IE10.

In Firefox the labels are cut and do not see all the text.

In IE10 the labels do not turn.

My changes:
.ct-chart .ct-label.ct-horizontal {
  font-size: 12px; 
  text-align: top;
  display: inline-block;
  transform-origin: 0% 0%;
  transform: rotate(90deg);
  -ms-transform: rotate(270deg);
  -ms-transform-origin: 0 0;
}

Any help?

Thanks! Plácido

**Comment by dagflater** [comment]
Hi there
I have some date labels and other graphs with text labels - and I only want to rotate the text ones.  Is there a way to do this in "options" that you send Chartist?  ie, rotateLabels: 45%

**Comment by malthe** [comment]
@gionkunz your labels are displaced in Chrome when zoom level is changed.
