### ISSUE TITLE
Is it possible to export a chartist chart as a image?

### ISSUE THREAD

**Issue by romanrdgz** [chartist-js/chartist#157]
I'm looking for the proper charting library for my web application, but I need to export the charts as image files to store them at the app database and/or share them at twitter/facebook.

Is this possible with Chartist.js? If not, will it be possible soon? Which would be an alternative? Thanks

**Comment by gionkunz** [comment]
Hey there. You could use a technique similar to this: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Drawing_DOM_objects_into_a_canvas

This would be a perfect example for a Chartist plugin http://gionkunz.github.io/chartist-js/plugins.html

**Comment by romanrdgz** [comment]
I'm afraid I'm not so fluent in JavaScript in order to figure out how to export to PNG from that article. I'll need to find a library for that, or use a different charting library

**Comment by gionkunz** [comment]
It's not such a big deal. Maybe this helps you? http://stackoverflow.com/questions/5433806/convert-embedded-svg-to-png-in-place

**Comment by romanrdgz** [comment]
It looks promising, but (correct me if I am wrong) that is a client-side solution. I want a server-side solution, so I can store users charts into a database.

I do understand javascript code, since I have been a developer for years in other languages. But when it comes to web application filesystem, I get a little confused, so I don't think I could addapt that code so I can store an image at server side.

**Comment by gionkunz** [comment]
Why do you need PNG? Is SVG not an option?

**Comment by romanrdgz** [comment]
I want to store it at server database, but also to share at
Facebook/Twitter, And I think it is Not possible to share a SVG file.
Moreover, I also wanted to set a watermark, for marketing purposes, and
that would be kind of hard with SVG

El viernes, 23 de enero de 2015, Gion Kunz notifications@github.com
escribió:

> Why do you need PNG? Is SVG not an option?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gionkunz/chartist-js/issues/157#issuecomment-71195471
> .

## 

Román Rodríguez

**Comment by sandstrom** [comment]
You could use phantomJS to render an image. Also, perhaps this is more suited for Stackoverflow than the issue tracker.

**Comment by nblackburn** [comment]
Not sure it as as it is rendered in plain SVG instead of on a canvas which this functionality comes from.

**Comment by gionkunz** [comment]
In the client you can render the SVG into a string and also render a style tag before the svg string containg all the style. Then you can prepend the string with a data URI notation and create an image element with this data URI as src. After this you can render this image in a canvas and export the canvas as PNG. The above links also describe that more or less. On server side PhantomJS could be used as already stated by @sandstorm.

**Comment by gionkunz** [comment]
Closing this issue for now

**Comment by mecampbellsoup** [comment]
@gionkunz @sandstrom is there not a simple node.js library which can take data + labels + configuration as input(s) and spit out an object which has a `chartObject.saveToFileSystem()` function in its API?

Not very experienced with JS, sounds like once I have an SVG file in memory/at runtime I can just write it to the filesystem (node's built-in `fs` module)...

**Comment by deQuota** [comment]
@mecampbellsoup 
I had the same problem generating images from chartist charts. It was difficult to generate images since chartist using <foreignObject> in svg as default (you can change this).

However I was able to generate clear images of chartist charts after some research, 
as a help for all I have created a npm module for that one
Hope this will help for all
https://www.npmjs.com/package/chartist-to-image

**Comment by haifzhan** [comment]
@romanrdgz  Have you found any helpful resources or have you solved the issue? I need to generate server-side charts in SVG/PNG format as well but don't know how to achieve this by chartist.js

**Comment by kalnode** [comment]
This is not a Chartist issue. This is a "how-can-I-programmatically-generate-image-snapshots-of-web-pages" issue.

With any chart library, simply generating images server-side is going to require a rendering step (one way or another) on your server, and that is work to be done. Most chart libraries are not going to do this for you because it's outside of their scope. You need to use 3rd party libs for this (like what @deQuota mentioned earlier).

Some chart libraries are canvas-based (like ChartJS), and have an edge here because inherently HTML canvas is easily exportable as a bitmap image. You can see it for yourself: right-click a canvas-based chart and simply save the image. IMHO, this capability alone isn't enough to beat SVG-based charts advantages (accessibility, responsiveness, scalability, etc).
