### ISSUE TITLE
Native SVG animations

### ISSUE THREAD

**Issue by martinsznapka** [chartist-js/chartist#163]
Hi everyone
Thx for this great charting library.

I have a question regarding native SVG animations:
http://oak.is/thinking/animated-svgs

Is it possible to use it within Chartist.js? How?

I am interested in some basic animations, like "grow" line chart or "open" pie chart ( http://goo.gl/vDtZXP ). Using 70kB SMIL javascript for executing basic animations seems to me too much and CSS animations couldn't probably handle it.

**Comment by gionkunz** [comment]
The animations explained on http://oak.is/thinking/animated-svgs are done using declarative SMIL animations. SMIL is very powerful but it's sometimes a bit impractical specially for dynamic animations based on input data.

In order to create SMIL animations within Chartist, we have added some convenience methods to our SVG library that allows you to make use of SMIL in a more practical way.

I've implemented your grow example on bar charts using the SVG animate function in combination with the draw events:
http://jsbin.com/suziv/1/edit

You can go further and explore the SMIL animation API of Chartist a bit more. There is some documentation in the API documentation but we should actually add more examples. The API is very powerful and your have almost limitless possibilities. You can also chain up animations by using the animation declaration object with array properties: http://jsbin.com/suziv/2/edit

Under the hood Chartist simplifies a few basic animation jobs by using a so called "guided mode". By disabling this guided mode you can use standard SMIL that also includes event based timers where you can reference other animation events as indicators to start a given animation.
http://jsbin.com/suziv/3/edit

There are a lot more possibilities and I recommend to read through the SMIL specification. Due to the simple object notation you can also easily offload your animation data into JSON files and load them as needed.

I hope this helps and thanks for opening up this topic! We really lack in documentation and examples here.

Cheers
Gion

**Comment by martinsznapka** [comment]
Hi Gion
Thank you for answer.

So Chartist directly use native SVG animations, very cool!
I don't know why I was confused, I thought I have to include additional ~70kB library for animations (snap.svg?) which do the animations "by yourself".

I was trying to modify your bar chart example to achieve "grow" animation on line diagram, but without success. The line is defined with data attribute in path element and it looks like complicated task to animate them.

You are completely right about examples, this would be very helpful for many developers.
Would be great if we have example of "growing" line diagram and "opening" pie chart.

Thank you
Martin

**Comment by martinsznapka** [comment]
Something like http://jsbin.com/ganejawuda/2/edit
But I guess the "from" and "to" have to be generated somehow by Chartist.

**Comment by gionkunz** [comment]
@martinsznapka animating a path is not that easy and requires shape morphing. I still have an open todo to include a path API in the SVG library within Chartist. This could cover basic path construction but also deconstruction as well as transformation. This way it'd be easy to create a path with all points set to the lowest value and then use this as a morphing source. I've create an issue for this #173

**Comment by gionkunz** [comment]
Hey @martinsznapka  this is now possible with the new SVG Path API. Check this example: http://gionkunz.github.io/chartist-js/examples.html#svg-path-animation

**Comment by martinsznapka** [comment]
Awesome!
Thx a lot.
