### ISSUE TITLE
How big data set your chart can handle?

### ISSUE THREAD

**Issue by denisvolokh** [chartist-js/chartist#17]
Hi,

I would like to use your chart in my project where I need to show about 20000 data points. 
Can your chart handle it?

And is there a way to show flags(label) at specific data point?

Thanks.

**Comment by gionkunz** [comment]
Short answer is no.

Chartist purpose is to be a simple responsive charting library and performance is definitely something we need to improve but 20000 data values is currently totally out of scope. In the future we could argue that a virtual data view should be possible using typed arrays and some sort of view representation in order to selectively show data but this is not in the near future. Also I think it's important to not miss the target of being a SIMPLE charting library for simple use-cases (like dashboards, simple contextual statistics etc.) that also work nicely on mobile. It's kind of hard to argue that a chart with 20'000 data elements falls into this category.

However, also for the sake of other questions that fall into this category, I've created a few JSBin's to illustrate some performance with different data count:

100 data points: http://jsbin.com/xiqoj/4/edit
1000 data points: http://jsbin.com/xiqoj/5/edit
5000 data points (without smoothing): http://jsbin.com/xiqoj/6/edit
10000 data points (without smoothing): http://jsbin.com/xiqoj/7/edit

On my machine (Chrome 36 32-bit on Windows 7 64-bit with i7 and 8 cores) I'd say that 10000 data points without smoothing is the limit. This is very individual I guess.

Cheers
Gion

**Comment by seyfer** [comment]
@gionkunz sadly examples do not work anymore.

**Comment by gionkunz** [comment]
I don't know why but the Sass with Compass tab seems to have an issue. Just delete the content there, worked for me.

**Comment by gionkunz** [comment]
Or just change it to CSS then it works ;-)
