### ISSUE TITLE
Create simple path API in Chartist.Svg

### ISSUE THREAD

**Issue by gionkunz** [chartist-js/chartist#173]
This API should allow the following but not limited to:
- Constructing a path via an easy JavaScript API (rather than string concatenation like done currently for the line chart)
- Deconstructing existing SVG path (parsing) and creating an object model that can be modified easily
- Modify path elements and apply transformations

This makes the line chart path constructions much more maintainable but also enables Dev's to intercept the drawing process and create their own paths, modify existing paths easily. Also this comes in very handy if one wants to animate paths and need to create morphing bases for an existing path.

**Comment by kyrasteen** [comment]
Hey there. Chartist has been enjoyable to work with, so thank you! 
One thing I am currently stuck on is trying to create a new path so that I can join it with an existing path (for an animation). 
Is there a way to generate the coordinates for a new path element (curve in my case) based on the final path element of an existing path and a new data value?

something like this:
```
  const pathToAppend = new Chartist.Svg.Path(false);
  pathToAppend.curve(lastPathElementOfExistingPath);
  pathToAppend.curve(?, ?, ?, ?, ?, ?, false, {
    value: { x: 1516387320000, y: 984 } , // new data value
  });
```
How can I generate the x, x1, x2, y1, y2 and y coordinates for the new curve element?
