### ISSUE TITLE
Minimum/maximum axis values

### ISSUE THREAD

**Issue by ilanbiala** [chartist-js/chartist#191]
It would be great to say `minX: 0` or `maxX: 10` so that our graph doesn't start at 1 and look a little confusing at first.

**Comment by gionkunz** [comment]
What about `low: 0` and `high: 10` ;-)

**Comment by gionkunz** [comment]
Tell me if that didn't helped.

**Comment by ilanbiala** [comment]
Right, but that only sets the y axis right? I looked through the defaults and didn't notice anything like that because I figured it would be in axisX or axisY, which probably make more sense as xAxis or yAxis.

**Comment by gionkunz** [comment]
Well X or Y is not really relevant here, they can also be switched now, at least for bar chart. low and high is for your data axis which by default is the Y axis.

**Comment by hansmaad** [comment]
Would be great to have low/high for both axes!

**Comment by gionkunz** [comment]
There is currently only one data axis that works with projected values. The other axis is step based and therefore does not require low and high. As soon as we have real XY charts it would make sense to have it on both of course.

**Comment by hansmaad** [comment]
XY Charts (incl log axes) are essential for our applications. I would love to use chartist. I really like it. Maybe I can contribute here? I have to choose a chart lib in the next weeks. Let me know if there are some issues I can help on...

**Comment by zambetti** [comment]
I interpret the original request to mean something like "minimumHigh" to set a minimum allowable value for the graph axis. So if the chart data only requires a Y axis of range 1, then a minimumHigh of 10 would ensure the axis is displayed with range 10; and if the chart data requires a Y axis of range 30, then a minimumHigh of 10 would have no effect and the axis would be displayed with range 30.

This is useful since graphs displaying integer data with a Y axis ranging from 0 to 1 are confusing.

I added this (below) to chartist.js getHighLow() function to allow for a new option named "minimumHigh". I'm not so familiar with the entirety of the source code, so there's probably a better way to support this, but this fix did the trick for me.

```javascript
  Chartist.getHighLow = function (data, options, dimension) {

  ...
    
    // Clamp high to minimum allowable value if defined
    if (options.minimumHigh !== undefined) {
        highLow.high = Math.max(highLow.high, options.minimumHigh);
    }

    return highLow;
  };
```
