### ISSUE TITLE
Add option to bar chart for category / series axis instead of time axis

### ISSUE THREAD

**Issue by gionkunz** [chartist-js/chartist#209]
It's also desired to have the series spread over the whole bar chart where each series will be represented as a single bar. One example would be the coffee consumption of your team where each team member has its own bar / represents a series.

**Comment by purplelady105** [comment]
I see that this issue is closed, but I was researching how to make each bar a different color in a stacked bar chart and got here from this post: https://github.com/gionkunz/chartist-js/issues/229 which is also closed. Is it possible now to make each bar a different color? I tried using chart.js since that library makes it very easy to control the bar colors, although now I cannot control the labels and tooltips as well as I can with chartist, so I would really like to use your library.

**Comment by twobob** [comment]
As far as I can see from this commit the colors themselves are still only determined internally. (why?)
Although the new option for bars does infact create a color for each bar.

```
new Chartist.Bar('.ct-chart', {
  labels: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
  series: [20, 60, 120, 200, 180, 20, 10]
}, {
  distributeSeries: true
});
```
Sadly that is not

```
new Chartist.Bar('.ct-chart', {
  labels: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
  series: [20, 60, 120, 200, 180, 20, 10],
  colors: ["#fff","#f0f","#f00","#00f","#000","#0f0"]
},
```
et cetera

that said. https://gionkunz.github.io/chartist-js/plugins.html#threshold-plugin would appear to have tools capable of adding color thru value so... could be the direction.  a nice and simple same-length array of SVG friendly colors as strings would be very low effort for the average user compared to creating an abstract plugin. 

EDIT:
And finally: 

>  Instead of specifying your colors, line width and other style related things in the JavaScript API, you'll need to use CSS in order to control your appearance.   

Hmm. That has limited application to this use case sadly.  I did note http://jsbin.com/kowida/2/edit?html,css,js,output however procedural injection of css is a pain.  perhaps it will be the only way

**Comment by GabrielChavesBorges** [comment]
> I see that this issue is closed, but I was researching how to make each bar a different color in a stacked bar chart and got here from this post: #229 which is also closed. Is it possible now to make each bar a different color? I tried using chart.js since that library makes it very easy to control the bar colors, although now I cannot control the labels and tooltips as well as I can with chartist, so I would really like to use your library.

In order to use each bar in a different color do this:

Add the following option to your bar chart:
distributeSeries: true

Add style to each bar using the following pattern in your css:
.ct-series-a .ct-bar {
  stroke: #36A2EB;
}

.ct-series-b .ct-bar {
  stroke: #FF6384;
}

Each series letter will represent the next bar (a, b, c, d..)

**Comment by twobob** [comment]
> 

Many thanks. sadly I stopped working on this project about 5 years ago?
