### ISSUE TITLE
How to stop line graph from substituting "0" if values are missing

### ISSUE THREAD

**Issue by 42hrs** [chartist-js/chartist#211]
Following is the data I'm using for a line chart. 

``` javascript
{
labels: ["Level 1", "Level 2", "Level 3", "Level 4"]
series: [
            {
              className: 'phy',
              name: 'Physics',
              data: [15, -5, -2, -3]
            },


            {
              className: 'chem',
              name: 'Chemistry',
              data: [-1]
            },


            {
              className: 'math',
              name: 'Mathematics',
              data: [10]
            },


  ]
}
```

There are 4 levels, and not all the subjects will have data for all levels. The default behavior is to resort to "0" if values are not available. For example, in Chemistry and Maths, Level 2, 3 and 4 are shown as zero on the graph.

Would it be possible to stop substituting 0, wherever values are missing?

**Comment by gionkunz** [comment]
Hi there. Handling missing values is very individual and therefore not part of the chartist core package. What behavior do you expect on missing data values? Should the line and points stop? What happens when you have holes in arrays eg. [4, 2, , , 4, 2, 1, , , , , 3]. Would you stop and start again with the next data value?

I believe there is some work ongoing to write a plugin for this @oliveraustria in #139. I'm closing this one as duplicate.

**Comment by 42hrs** [comment]
In my case, after the values stop it won't start again. I just have to stop drawing the lines, instead of drawing it back to 0. I will take a look at the issue you mentioned. Thanks @gionkunz

**Comment by oliveraustria** [comment]
Hey, you can find some new example of the plugin here: 
http://oliveraustria.github.io/chartist-plugin-missing-data/

**Comment by gionkunz** [comment]
Hey @oliveraustria , how about you create an entry for your plugin on the Chartist documentation page? https://github.com/gionkunz/chartist-js/blob/develop/site/data/pages/plugins.yml#L47-L150
