### ISSUE TITLE
Log Scale

### ISSUE THREAD

**Issue by MarkLyck** [chartist-js/chartist#236]
I havn't been able to find any documentation on using logarithmic scales with chartist.

This is such a basic feature, that any grap-library absolutely needs. Mostly when working with exponentially growing/declining charts, you NEED a log scale to properly visualize that data.

Is this really not possible to have a logarithmic y-axis with Chartist.js?

Or simply a way for me to specify the y values manually?

E.g. my data right now, goes from 0 to 500,000,000 in 1 y axis value. (making it impossible to properly show my data, over the first 300 x-values) - (my data is basically flatlining, when there's really a massive exponential increase).

**Comment by Hammster** [comment]
Well there is an pull request open, that still need to be reviewed and tested.But @gionkunz will have to tell you if there is an ETA.

https://github.com/gionkunz/chartist-js/pull/185

**Comment by gionkunz** [comment]
I still need to review #185 and I have no ETA since I got other things in my way currently. If you want to risk branching you can go ahead and use #185 directly. Although I agree log scale is something natural in Charts, I'm not sure if it fits the core claim of Chartist (A simple and responsive charting library) the same way as it would not fit into Chartist to have financial charts, map charts and so on. However, if we find an easy and non intrusive way to integrate a log scale without bloating the code, I'm more than happy to add this feature. I'll give the pull request, which is rather large, a spin once I got more time again and hope that this will be soon.

**Comment by hansmaad** [comment]
Do we really need a new chart type? Can't we just have a LineChart and configure both axes from LinearAxis, LogAxis, StepAxis? I would also appreciate if the llibrary was more modularized if we have more and more feratures. I would love to use the core chartist/chartist.js and add chartist/line.js, chartist/logaxis.js

**Comment by gionkunz** [comment]
@hansmaad, yep thats the plan. Ideally we want the line chart to have both axis configurable. Modularization is already in place but its not advertised nor distributed like this. It would be already possible to only use core and bar for example. Maybe not relevant to this but Im planing to rewrite the whole library in ES6 and use ES6 modules for each component. The transpiled version would somehow need to shim back into namespaces. For 1.0 however, we should focus on the current code and provide charts with exchangable axis (which shouldnt be too much effort, and i still need to chek the PR whats already there)

**Comment by gionkunz** [comment]
Closing this issue in favor of #64
