### ISSUE TITLE
Gauge height

### ISSUE THREAD

**Issue by informa** [chartist-js/chartist#240]
Hi I am adding a couple of charts to a project and I was playing with the gauge chart but it looks like the height of the svg also includes the space that is not visible: ie the other half of the donut. Is there a way for the elements to fill the viewport? Noticable when aligning with a different chart. Mucking around with the aspect ratios kind of worked but as said the space is included in the svg.

![screen shot 2015-03-20 at 4 12 10 pm](https://cloud.githubusercontent.com/assets/726265/6746432/3d93a99a-cf1c-11e4-87d8-c6f7702655a5.png)

**Comment by Hammster** [comment]
You can manipulate the svg height value with css, it will only effect the outer svg box. so 50% height on svg.ct-chart-pie should do the job. But you'll have to test if it works since i cant do it from work at the moment, eventually use !important.

But keep in mind to pre set an identifier for gaugecharts something like .ct-chart-gauge. so that the other graphs are not affected.

**Comment by informa** [comment]
Thanks for that, it did the trick.

**Comment by EvanWieland** [comment]
In case anyone wants a live demo on how to fix this: [http://codepen.io/EvanWieland/pen/bpjrog](http://codepen.io/EvanWieland/pen/bpjrog). This solution also maintains proper chart height during browser resize thanks to the `created` event.
