### ISSUE TITLE
Using fixed width foreignObjects for drawing chart labels

### ISSUE THREAD

**Issue by dsbudiac** [chartist-js/chartist#25]
**Is there anyway to support multi-line labels at the moment?** I'm hitting a dead end in populating a bar chart... I cannot simplify axis labels any further, and as a result, some xAxis labels are overlapping.

**Comment by gionkunz** [comment]
Hi, afaik text wrapping would need to be implememted by us as there is nothing like a text box already there. Altough this would not be too much of a problem, maybe there are other ways to get around this? One thing I like to do when space gets tight in chartist is to omit every n label (if thats an option) by using a labelInterpolationFnc like this:

``` javascript
function(value, index) {
  return index % 3 === 0;
}
```

The signature of the interpolation function is not well documented i just realized.

Cheers
Gion

**Comment by dsbudiac** [comment]
Yeah I've used that technique for a couple of charts already. However in this particular bar chart type, each label represents a distinct category (rather than a rough scale that can be inferred when some labels are hidden). Hiding some labels would make it confusing for the reader.

**Comment by gionkunz** [comment]
I guess this would best be done with foreignObjects. https://developer.mozilla.org/en/docs/Web/SVG/Element/foreignObject

**Comment by LeoIannacone** [comment]
Another way (not so smart, neither so "responsive") could be split labels on '\n' (or "< br />") and then fill the object with tspan elements...

**Comment by gionkunz** [comment]
Yeah, the problem with tspan is that you need to offset them using relative coordinates and this is really a pain specially when you want to rely on CSS to style your labels with any font, size and line-height. Also configure word wrap via CSS is nice. Let's focus on foreignObject to use `<span>`'s first to see how it integrates. If this is also getting to hairy we still have the tspan objects in the back pocket.

**Comment by gionkunz** [comment]
I've included an easy way to create foreignObjects in Chartist and it's also very easy to substitute labels by using the draw events of chartist 0.2. You can run this example code on the live examples page of the doc site.

I think though that it would probably make sense to make the labels always foreignObjects within Chartist and that we change the way the labels are handled. Currently Chartist is creating all labels in beforehand just to estimate the maximum label width. With that it will auto arrange the area of the chart. Maybe we need to change this so that it allows you to specify a fixed label width for the y axis. Lets see.

```
var chart = Chartist.Line('.ct-chart', {
  labels: ['Long labels are bad', 'specially for repsonive design', 'and if they cannot be wrapped', 'you have a real problem', 'thats for sure'],
  series: [
    [12, 9, 7, 8, 5]
  ]
}, {
  axisX: {
    offset: 80
  }
});

chart.on('draw', function(data) {
  if(data.type === 'label' && data.axis === 'x') {
    var textHtml = ['<p>', data.text, '</p>'].join('');
    var multilineText = Chartist.Svg('svg').foreignObject(textHtml, data.x, data.y - 80, data.space, 80, 'ct-label');

    data.element.replace(multilineText);
  }
});
```

**Comment by gionkunz** [comment]
After some performance analysis of Chartist I've found that the biggest performance bottleneck currently is the drawing of the labels. Currently Chartist does create them by creating dummy lables with the label CSS classes in order to find the largest label. Based on this Chartist will adjust the available drawing space. This has the nice effect that you don't need to fix your label width and it's done automatically by Chartist, but the problem is we need to use clientWidth on each label which causes CSS reflows (1 x for each label on the chart!).

We started out here with the idea to use foreignObjects for labels so that they can be multi-line. Initially I thought it'd be a nice idea to also provide the standard SVG text labels also for the purpose of the auto sizing feature. However, after the latest findings I'm not so sure about this anymore, and I'd recommend that we go for the foreignObject labels only.

**foreignObject multi-line solution vs. SVG text elements with auto-sizing**
- pro foreignObject
  - Labels are like absolute positioned HTML block elements so they can be styles with CSS like regular elements (the element is actually a <span>)
  - They support multi line and text wrapping like any other HTML element and you can also use things like word-wrap, white-space etc.
  - When the chart is created we don't need to pre-measure label width so we don't do reflows like before (I think there will be 2 reflows only Vs. 2 + as many labels as exist)
  - Even though the auto-sizing is no longer working this has also a good part as the design looks more harmonic when label areas on different charts all have the same width
- con froeignObject
  - As the label area width can no longer be auto calculated one would need to override the default label width in the options for adjustment.
  - Maybe browser support? I didn't dig too deep into the past yet.

I'd really appreciate some feedback here guys. I've created a branch with the changes https://github.com/gionkunz/chartist-js/tree/fixed-size-foreign-object-multi-line-labels

You can also just mess around a bit with this codepen to get a feel for the new configuration http://codepen.io/gionkunz/full/d046898d38713d4351670905b855ef81/

If the feedback for this change is good then I'll merge this branch into develop.

Cheers
Gion

**Comment by gionkunz** [comment]
This has been merged into develop with a text element fallback for browsers which don't support SVG 1.1 Extensibility (mainly IE)

**Comment by rebeccaswebsite** [comment]
Hi there, I was wondering if it would be possible to use this text element fallback, even if your browser supports foreignObjects? I'm trying to export my charts to a pdf, and I'm not able to use the foreignObject labels in the pdf.

**Comment by rebeccaswebsite** [comment]
update for anyone finding this: I've managed to change the foreignObject elements into text elements using JavaScript so the labels are displaying properly now
