### ISSUE TITLE
Make code pass Google Closure Compiler minification without setting to ECMA5

### ISSUE THREAD

**Issue by exside** [chartist-js/chartist#278]
This part of the core code:

``` javascript
    return {
      get currentOptions() {
        return Chartist.extend({}, currentOptions);
      },
      removeMediaQueryListeners: removeMediaQueryListeners
    };
```

makes the Google Compiler fail, the "get ..." is the problem here, which is ECMA Script 5....

I completely understand that the code of chartist.js doesn't care about IE8, as it doesn't support SVG anyways, but even when no charts are displayed I'd like to avoid a complete break of the page in IE8 because of that "too modern" code =)...any tips how to convert this to to ECMA3?

**Comment by exside** [comment]
maybe something in this direction?

``` js
    if (Object.prototype.__defineGetter__ && !Object.defineProperty) {
      Object.defineProperty = function(obj, prop, desc) {
        if ('get' in desc) obj.__defineGetter__(prop, desc.get);
        if ('set' in desc) obj.__defineSetter__(prop, desc.set);
      };
    }

    Object.defineProperty(Chartist.prototype, 'currentOptions', {
      'get': function() { return Chartist.extend({}, currentOptions); }
    });
```

**Comment by exside** [comment]
Or just replace

``` js
      // replace current code
      // get currentOptions() {
      //   return Chartist.extend({}, currentOptions);
      // },
      // with
      currentOptions: Chartist.extend({}, currentOptions),
      removeMediaQueryListeners: removeMediaQueryListeners
```

I did that and it compiles and seems to work, any drawbacks with such a change?

**Comment by gionkunz** [comment]
@exside I'd be fine with `currentOptions: Chartist.extend({}, currentOptions)` although, as you said, we don't support < ECMA5. As this is the only place where the lib could fail with a ECMAScript 5 polyfill, I guess it makes sense to replace this. Can you make a PR?

Cheers
Gion

**Comment by gionkunz** [comment]
Hmm.. the problem is that it's already exposed as a property not as a function. And `currentOptions: Chartist.extend({}, currentOptions)` will always point to the initial currentOptions but won't be updated of course.

I'd be fine with a `defineProperty` so the syntax stays free of ECMA5, but definitely without the defineProperty polyfill. If someone really needs Chartist in a JavaScript environment with < ECMA5, they would anyway need to use something like `es5-shim` which will include a defineProperty polyfill anyway.
