### ISSUE TITLE
Error on charts that are hidden first

### ISSUE THREAD

**Issue by Martinomagnifico** [chartist-js/chartist#282]
Hi Gion, I really like Chartist, and I think it is the way to go compared to other charting libs. At the office we use KendoUI Dataviz, but I don't like the way how we have to put the styles into the JS. So I'm testing Chartist a lot these last few days. Right now I get some new errors:

I have multiple charts on a single page. But some content is hidden, and made visible by clicking tabs (Bootstrap). This leads to two kinds of errors. 

The first error is that charts in hidden areas are not rendered, so that when the tab is made visible, the chart is still NOT visible. This can be fixed by re-calling the function that builds the charts. 

The second error is not immediately visible, but can be seen in the console:

```
    [Error] Error: Invalid value for <foreignObject> attribute height="NaN"
    (anonymous function) (chartist.min.js, line 7)
    (anonymous function) ([native code], line 0)
    forEach
    e (chartist.min.js, line 7)
    d (chartist.min.js, line 7)
    f (chartist.min.js, line 7)
    f (chartist.min.js, line 7)
    k (chartist.min.js, line 7)
    createLabel (chartist.min.js, line 7)
    (anonymous function) (chartist.min.js, line 7)
    forEach
    createAxis (chartist.min.js, line 7)
    d (chartist.min.js, line 7)
    h (chartist.min.js, line 7)
    h ([native code], line 0)
```

Is this fixable, or can the error be suppressed?

**Comment by gionkunz** [comment]
Hi there

Thanks for your interest in Chartist. Chartist relies on the container width and height to render correctly. Hidden elements do not provide this and therefore Chartist is running into an issue.  This issue was all about that https://github.com/gionkunz/chartist-js/issues/119

In regards to the error I think we should prevent it. Also it will fix some issues with rendering frameworks that eventually create charts offscreen And add later to the document. 

We should also add an example of this situation in the getting started documentation.

**Comment by gionkunz** [comment]
In the meanwhile its important that you move the creation of your chart into an event handler when a tab was activated.

**Comment by gionkunz** [comment]
Closing this issue in favor of #287
