### ISSUE TITLE
NS_ERROR_FAILURE inside Bootstrap modal

### ISSUE THREAD

**Issue by baldown** [chartist-js/chartist#286]
I am working on making a Bootstrap modal present a graph built by Chartist.  I have graphing code that works great outside of being used with the modal, and modals that work great when presenting other content, but when I put them together, I get Firefox reporting NS_ERROR_FAILURE and no graph renders inside the modal.  

When I view it on Chrome, the graph starts to graph and then fails with the error:
Error: Invalid value for <foreignObject> attribute height="NaN"

I'm not 100% certain this is a chartist bug necessarily, but it's eerily similar to issue #102.  As in #102, resizing the browser in Chrome makes the graph render, though this doesn't work in Firefox.  Is there 
something I'm doing wrong here, or is this some kind of bug?  

I have a jsfiddle reproducing the issue here: http://jsfiddle.net/qw2Lnqng/4/

Thanks

**Comment by baldown** [comment]
Bah, I fight this issue on and off for 3 solid days and can't find a solution, and then I report this as an issue here, only to find the solution 5 minutes later.  The solution is that I can't execute the Chartist javascript until the shown.bs.modal event fires on the moda, and this resolved the matter.  Apologies.

**Comment by gionkunz** [comment]
Hey there. I'm sorry about the troubles you had with Chartist. Your issue was also already discussed in #119 .

We will use #287 to cover this with documentation.

Cheers
Gion

**Comment by GianniCristian** [comment]
Hi, I'm facing the same problem listed above: http://jsfiddle.net/qw2Lnqng/4/ (just copy and paste).

I can read the solution but I'm not able to solve the problem by myself. Can you please provide the solution in the fiddle? I have tried different way but I'm not an expert in javascript. I understand that the problem is regarding the display:none as described here: https://github.com/gionkunz/chartist-js/issues/119.

Thanks for your time!
Gianni
