### ISSUE TITLE
Adding a stepped line interpolation to Chartist

### ISSUE THREAD

**Issue by gionkunz** [chartist-js/chartist#295]
Sometimes it's nice to have a stepped interpolation like here: http://www.clearlyandsimply.com/clearly_and_simply/2011/04/an-underrated-chart-type-the-band-chart.html

A stepped interpolation function can be added to https://github.com/gionkunz/chartist-js/blob/develop/src/scripts/interpolation.js.

**Comment by Martinomagnifico** [comment]
Hi Dion, I tried this:

```
Chartist.Interpolation.step = function() {
return function cardinal(pathCoordinates) {
  var path = new Chartist.Svg.Path().move(pathCoordinates[0], pathCoordinates[1]);

  for(var i = 2; i < pathCoordinates.length; i += 2) {
    var prevX = pathCoordinates[i - 2],
        prevY = pathCoordinates[i - 1],
        currX = pathCoordinates[i],
        currY = pathCoordinates[i + 1]
    path.line(prevX,prevY);
    path.line(prevX,currY);
    path.line(currX,currY);
  }

  return path;
};
```

  };

But while it does draw an extra straight line-segment, it doesn't draw an extra dot there if showPoints is true. (And if an extra point is drawn there, I think there should be a check for the values, because you don't want to draw two of those dots if there is no change in Y-value, because then you draw them at the same location)

**Comment by gionkunz** [comment]
Maybe we could use the interpolated path to create dots instead of the raw coordinates? I'll try if that works. Thanks for your work!

**Comment by gionkunz** [comment]
I have this working on my local dev. I've re-written the interpolation functions and Svg.Path to support this use-case. I'll add your interpolation function and try the result.

**Comment by Martinomagnifico** [comment]
Cool. Thanks!
