### ISSUE TITLE
horizontal bars - several issues with label text of y-axis

### ISSUE THREAD

**Issue by acki-m** [chartist-js/chartist#297]
I am evaluating chartist, because of its responsive abilities.
However, there are several issues I found:
1)
First how can I vertical center the label text of the y-axis?
Take a look here:
http://output.jsbin.com/kokuxasoqu/1/
The label text should be in the middle of the horizontal bar.
This should be default behavior, no coding should be involved to fix this.
2)
More annoying is the horizontal placement of the label text:
![chartist_horizontal_bar_issues](https://cloud.githubusercontent.com/assets/11368160/7444641/aa79d9ce-f18d-11e4-9cdb-09a5c31a5e62.jpg)
Why is the label text overlapping the content of the bars?
Using the option:
`axisY: { offset: 70 }` to fix this, is the wrong approach. 
I don't want to move the yaxis independent of the label width, I also don't want to insert some magic numbers..

**Comment by gionkunz** [comment]
Hi

1) Horizontal bar charts were introduced just recently. For line charts this behavior is desired as the label should be close to the line. For bar charts centering is desired I agree. However, this feature is not implemented yet. Also you need to consider that the story is different for IE as it wont support `foreignObject`. However, for `foreignObjects` containing spans there's an easy solution which should go to the Chartist CSS for bar charts I agree:

``` css
.ct-chart .ct-label.ct-vertical {
  display: flex;
  align-items: center;
  justify-content: flex-end;
}
```

For 2 this was actually part of Chartist once. The required space by all text labels was evaluated and then the `chartRect` was calculated based on this. I personally think that if you'd like to have consistent charts, this needs to be set manually and also this way you can control how your chart text wrap works. Otherwise, how would you decide if the available label width should be extended or if a new line should be created? There are just many factors there so the easiest and most flexible solution was to make it configurable but also implies that you NEED to configure it. Maybe we can add this feature again by having the multi line feature configurable and if it's disabled, we can again calculate the largest label and extend the space needed for the labels. Anyway, we should open two separate issues for those concerns.

**Comment by gionkunz** [comment]
I've created #303 and #304 for this. Let's discuss there.
