### ISSUE TITLE
Label positioning (Pie Chart)

### ISSUE THREAD

**Issue by lindekaer** [chartist-js/chartist#299]
Hi,

I have a small issue, with a slightly offset label - I was just wondering what causes, in this case, the '7%' to not be centered in its slice? Should these minor cases be fixed manually or is there a better way? I suspect that the addition of percentage makes it looked skewed. 

Thanks for a great tool!

![screen shot 2015-05-04 at 08 14 15](https://cloud.githubusercontent.com/assets/4806217/7449409/de5e0d3e-f235-11e4-9742-0427c1b70287.png)

**Comment by gionkunz** [comment]
it looks like the label is aligned with `text-anchor: start;` Did you set the Pie option `labelPosition` to `explode` ? http://gionkunz.github.io/chartist-js/api-documentation.html#chartistpie-declaration-defaultoptions

**Comment by Martinomagnifico** [comment]
Actually, the 7% IS centered in its slice, so the problem is not the %. The problem is that the the label is placed on a baseline, which itself is placed in the exact center of the slice. 

![untitled-2](https://cloud.githubusercontent.com/assets/380576/7582859/ae65a788-f891-11e4-9665-02baa6a95e65.gif)

I wouldn't know how to fix this, as the font-size should as variable as well.

**Comment by gionkunz** [comment]
You always need to remember that this is a SVG text element (at least in the Pie Chart). So you can use the SVG style property `alignment-baseline: middle;` to achieve this. I guess as this is probably required mostly, we should add the property to the default styles of the pie chart labels.

**Comment by gionkunz** [comment]
Please re-open if this issue still persists.

**Comment by stapucar** [comment]
What is the difference of labelPosition and labelDirection?
