### ISSUE TITLE
Make axisses offset 0 if showLabel = false

### ISSUE THREAD

**Issue by rbozan** [chartist-js/chartist#301]
if showLabel is currently false, you basically don't have a X axis. there's no data being shown there, however the offset is still being the original value despite that there's nothing to show there.

**Comment by gionkunz** [comment]
Hey there. I agree with you, however I think we should deprecate the axis offset configuration and only use the new padding. This is tracked under #214 

Do you think if the label gets disabled we should then remove the padding on the given side? We could do that. However, if someone wants to keep the padding to provide consistent look of his charts (because others still have labels and they should all have the same padding) then he'd not be able to configure it. I'd be very careful with enforcing a configuration. 

We could say that if the defaults were not overriden in the padding, then we could remove it. We can assume that if `chartPadding.left` is still `undefined` in the options and `showLabel` is false, it would be okay to not use the default and set it to 0.

This will could also be implemented in the context of #304 and #214

**Comment by rbozan** [comment]
Yeah, exactly like you said would be fine. If it's undefined set it to 0.

**Comment by gionkunz** [comment]
I'll close this issue as the enhancement is tracked with #304 and #214
