### ISSUE TITLE
Rounded Corners for Donut Chart?

### ISSUE THREAD

**Issue by CalebKester** [chartist-js/chartist#31]
Is there an option to round the corners for a [donut chart that isn't a full 360 circle](http://gionkunz.github.io/chartist-js/examples.html#gauge-chart)

**Comment by gionkunz** [comment]
You can use stroke-linecap: round; for this. Unfortunately this will make the stroke round on both ends, which looks a bit weird and is maybe not the thing you like. We could also draw the donut chart with shapes instead of strokes, but I really love the flexibility of strokes to be styled with CSS.

**Comment by CalebKester** [comment]
Can you add an option to invert the rendering of the svgs? That way they stack on top of each other in reverse order.  

To give you a little context, I'm just trying to do a 2 series donut chart. Similar to what you see here: http://anthonyterrien.com/knob/ but I like your library and using svg's better.

**Comment by gionkunz** [comment]
I was thinking of this use case when I create the donut pie chart and reversing the order actually makes sense for this and does not impact other use cases I can think of. I'm working on some other things in that area just now and will include this in a commit. Cheers

**Comment by mattbrailsford** [comment]
Can you give an example of setting the render order of a donut chart?
