### ISSUE TITLE
Pie slices occlude labels

### ISSUE THREAD

**Issue by tonyjmnz** [chartist-js/chartist#357]
Depending on the order of the `<g>` elements in the dom, one slice may occlude the label of another. This could be solved by placing all `<text>` elements after all `<g>` elements but it seems like this change could be hard to make given the current structure.

![screen shot 2015-06-18 at 1 46 27 pm](https://cloud.githubusercontent.com/assets/2080075/8241894/c08cb82e-15c0-11e5-809d-064c088dea61.png)

Source HTML in case it's useful:

`<svg xmlns:ct="http://gionkunz.github.com/chartist-js/ct" width="100%" height="100%" class="ct-chart-pie" style="width: 100%; height: 100%;"><g class="ct-series ct-series-c"><path d="M322,5A170,170,0,1,0,428.993,307.108L322,175Z" class="ct-slice-pie" value="6992"></path><text dx="241.8270336191411" dy="203.23642083716828" text-anchor="end" class="ct-label">6.83 TB</text></g><g class="ct-series ct-series-b"><path d="M428.532,307.48A170,170,0,0,0,482.542,230.913L322,175Z" class="ct-slice-pie" value="1016"></path><text dx="391.37252976200057" dy="224.11671929618618" text-anchor="start" class="ct-label">0.99 TB</text></g><g class="ct-series ct-series-a"><path d="M482.346,231.473A170,170,0,0,0,322,5L322,175Z" class="ct-slice-pie" value="3496"></path><text dx="391.37252976200057" dy="125.8832807038138" text-anchor="start" class="ct-label">3.41 TB</text></g></svg>`

**Comment by gionkunz** [comment]
Yeah that's not nice :-) I guess it would make sense to draw the labels outside the series group into it's own group similar to the line and bar chart and have this group laying above the actual Pie / Donut. The change isn't hard really. The group could be create before the series get created and then during the creation of the series, labels could simply be added to this group rather than the series groups. If you feel like and got some time I'd be more than happy about a PR :-)

**Comment by tonyjmnz** [comment]
PR368 seems to solve it, your proposed solution worked nicely :) thanks for such a cool library

**Comment by gionkunz** [comment]
This will go in 0.9.2 today. Thanks for the PR!
