### ISSUE TITLE
Fixed AxisY for Bar chart?

### ISSUE THREAD

**Issue by ErikTech** [chartist-js/chartist#363]
Hi there, I am currently loving this library, however I noticed that this option code only works for Line graphs:

<code>
axisY: {
  type: Chartist.FixedScaleAxis,
  ticks: [1, 5, 7.5, 8, 14]}
</code>

Is there a way to set the axisY ticks on a barchart as well? The labelInterpolationFnc simply writes over it and does not change any sort of actual dimensions/calculations of the graph.

I want to be able to specify a high and a low, or perhaps manipulate the axisY data in someway before the graph is drawn.

Thanks!

**Comment by gionkunz** [comment]
I still have some changes in my stash from working on 0.9 for enabling the bar graph to use axes dynamically. The thing is that there it's quite complex as the stacked and grouped bars as well as flipping bring more complex requirements. However, I'm confident my pending changes will land in 0.9.1 very soon.

**Comment by ErikTech** [comment]
Thank you for the response, I look forward to the update. 

Is there currently a way to set the number of ticks that show on the bar graph? I noticed that
<code> scaleMinSpace: 24,</code>
changes this but it would be great if there were a way to specifically set this.

**Comment by gionkunz** [comment]
The bar graph uses a `AutoScaleAxis` for the value axis that is currently statically wired. The purpose of the `AutoScaleAxis` is to use `scaleMinSpace` to figure out the best possible count of ticks automatically. In order to specify ticks manually, the `FixedScaleAxis` axis should be used but this can only be changed in the bar chart after I've refactored the code to make the axes configurable in the bar chart. In the meanwhile I've published 0.9.1 with some bug fixes and this will come with the next patch release 0.9.2 (except we have an other bugfix release in between)

**Comment by gionkunz** [comment]
This is now on the dev branch. Can you do some testing?

**Comment by SilvioLi** [comment]
Hi @gionkunz, I am trying to set a max Y of 24, but it keeps showing 25 instead.

I tried 24,23,22,21; but only 25 or 20 appears in the chart.

I used high:24 or/and FixedScaleAxis: 24, but neither worked for me.

<img width="586" alt="capture" src="https://cloud.githubusercontent.com/assets/17534190/19825626/701a51c8-9d30-11e6-9383-3e23d39e3280.PNG">

**Comment by gionkunz** [comment]
Yes this is because of the order of magnitude and the AutoScaleAxis. Low and high is only a referemce value. You can use a FixedScaleAxis. Check the switching axis type documentation on the getting started page.

**Comment by SilvioLi** [comment]
Thanks once again @gionkunz. I've been using it FixedScaleAxis wrong.
It's all good now.
