### ISSUE TITLE
ToolTip appears at the wrong location; Firefox 39+

### ISSUE THREAD

**Issue by mewcrazy** [chartist-js/chartist#381]
Hello,

In Firefox 41 Developer Edition, the tooltips appear at the wrong location. See the attached image:

![tooltips](https://cloud.githubusercontent.com/assets/6299479/8648376/6fa1eb74-2960-11e5-86d3-49a30e971a42.jpg)

Kind Regards,
Dennis Bitsch

**Comment by mewcrazy** [comment]
Exact Build: 41.0a2 (2015-07-12)

**Comment by leosilvano** [comment]
I'm using Firefox 39.0 on Ubuntu and i have the same issue... 
![screenshot from 2015-07-13 15 15 12](https://cloud.githubusercontent.com/assets/7308822/8657108/22bf1ac2-2972-11e5-8aee-b67d8b354462.png)

**Comment by wedgef5** [comment]
This is due to the fact that Firefox 39 finally implemented offsetX and offsetY on mouse events.  The problem is...they implemented it differently than other browsers.  The relevant Bugzilla entry is [here](https://bugzilla.mozilla.org/show_bug.cgi?id=69787).

Firefox's offsets are relative to a different element than other browsers.  In the case of Chartist, it appears that its offsets are relative to the SVG element that your mouse is over, thus you get relatively low offsetX/Y values.  Other browsers seem to be giving an offset relative to the parent container.  The Bugzilla issue makes reference to the spec not being terribly clear which is correct.

Unfortunately, I don't know what the right way is to fix this.  For the time being, I removed the reference to offsetX and offsetY in the positioning code and just let it use originalEvent.layerX/Y for all browsers.  From what I am reading at Stackoverflow, those attributes are deprecated and soon to be removed by Chrome and Safari (at least), so a better solution is needed.

Matt

**Comment by nicolaschenet** [comment]
Hey guys, I'm also facing this problem right now. Inverting `event.offset` and `event.originalEvent.layer` actually solves it, thus temporarilly.

Which leads to: 

``` javascript
  $chart.on('mousemove', function(event) {
    $toolTip.css({
      left: (event.originalEvent.layerX || event.offsetX) - $toolTip.width() / 2 - 10,
      top: (event.originalEvent.layerY || event.offsetY) - $toolTip.height() - 40
    });
 });
```

in chartist-plugin-tooltip, line 86
I think I should make a PR :)

As @wedgef5 just said, in FF, we can't rely on offsetX and offsetY when hovering a chart "point", if you always show the tooltip you'll see its position is always correct, until you hover a point ('.ct-line' in this case). Will have to find a better solution, but it can help for now.

:warning:  **Note: I'm using Chartist v0.9.1**

**Comment by abuisman** [comment]
What is the status on this? I can still confirm this bug on the example page at least.

**Comment by gionkunz** [comment]
Please file this issue again in the chartist-tooltip-plugin repository. I'll close this issue here. Make sure to reference it!

**Comment by ghost** [comment]
New code is not working in Chrome. I have added browser detection and it works fine now.

```
var left = (event.originalEvent.layerX || event.offsetX) - $toolTip.width() / 2 - 10;
            var top = (event.originalEvent.layerY || event.offsetY) - $toolTip.height() - 40;
            if(!isBrowser("firefox")){
                left = event.offsetX - $toolTip.width() / 2 - 10;
                top = event.offsetY - $toolTip.height() - 40;
            }
```
