### ISSUE TITLE
Add option that allows reversing or inverting line charts

### ISSUE THREAD

**Issue by aarai** [chartist-js/chartist#382]
I cannot find an option in the documentation where the numbering on a line graph can be reversed so that it is ascending instead of descending.

**Comment by joeporterme** [comment]
I was wanting to do this too.  Would be great

**Comment by gionkunz** [comment]
By numbering you mean the value scale that goes down vs. up right?

**Comment by aarai** [comment]
Yes that's correct.

**Comment by gionkunz** [comment]
This is not possible with simple configuration. However, you could transfrom the data into negative values and configure the labelInterpolationFnc to display the positive value again. This kind of mimics a inverted chart.

http://jsbin.com/xoqulakite/edit?js,console,output

**Comment by joeporterme** [comment]
Awesome, that worked perfectly for me!  Thanks so much!

**Comment by philmccarty** [comment]
This really should be in the docs somewhere. It's very valuable and I almost ditched the library til I saw this thread.

**Comment by ajhsu** [comment]
The approach that @gionkunz provided is simple and elegant, and it works perfect, thanks a lot!
And I also agreed with what @philmccarty said; Instead of leaving it in the issue, this should be placed somewhere in the docs. It will be helpful for those people like me, who is trying to make a ranking chart like https://github.com/gionkunz/chartist-js/issues/556.

**Comment by whiteonion** [comment]
`showArea: true` doesn't work with inverted chart like described in example. Is there a workaround?

**Comment by whiteonion** [comment]
`showArea: true` doesn't work with inverted chart like described in example. Is there a workaround?
