### ISSUE TITLE
TypeError: b.normalized[g].forEach is not a function

### ISSUE THREAD

**Issue by nubela** [chartist-js/chartist#393]
Trying out Chartist by cloning master branch and using *.min.js and *.min.css in my code, while following http://gionkunz.github.io/chartist-js/getting-started.html . And I get the error

```
TypeError: b.normalized[g].forEach is not a function
```

Reproduced on Safari/Firefox/Chrome.

What am I doing wrong?

**Comment by gionkunz** [comment]
Can you reproduce it on JSBin with the latest version? http://jsbin.com/qerojadunu/edit?html,js,console,output

**Comment by nubela** [comment]
Seems to work on jsbin. I suppose its a bug on my side. I'll close this issue, and if I can reproduce it, I'll re-open it again. Thank you!

**Comment by LaxisB** [comment]
i managed to stumble on this issue too.

it happens, if the chart series is a 1-dimensional array instead of a two-dimensional one

here's a codepen with the error: http://codepen.io/laxis/pen/eNxaJJ?editors=001  
jsbin: http://jsbin.com/vebegeyeki/1/edit?html,js,console,output
debugger screenshot:
 ![](http://i.imgur.com/szO5zb7.png)

hope it helps :)

**Comment by gionkunz** [comment]
Thanks for reproducting on jsbin! This make things a lot easier :-)

Series should always be an array of arrays! It's an array of data series.

http://jsbin.com/cuxama/edit?html,js,console,output

Cheers
Gion

**Comment by gionkunz** [comment]
Only pie charts or bar charts with the `distributeSeries` options are one dimensional arrays.

**Comment by eudennis** [comment]
That's just solve my problem too ;) thanks!
