### ISSUE TITLE
Hover states

### ISSUE THREAD

**Issue by herkyl** [chartist-js/chartist#4]
It would be nice to have hover data on PC and touch tooltips on mobile.

**Comment by gladson** [comment]
:+1:

**Comment by gionkunz** [comment]
Thanks for opening an issue. Actually I was thinking about adding an API for such things a lot but I came to the conclusion that we won't add functionality like this to Chartist.

The reason for not including this is simply that, while using inline-svg, a proper, semantic and annotated DOM, it's so simple to add this functionality yourself. It would pollute the library with stuff that is not the main concern of Chartist, which is only the drawing of the chart.

If you like to have behavior added to your charts you can do that with a few simple lines with using the DOM library of your choice.

Check out this JSBin (which is actually a very bad example because you should to this kind of visual only behavior with CSS, but it shows how easy it is)

http://jsbin.com/yisaye/1/

**Comment by herkyl** [comment]
Thanks for the reply. You should put some examples of how to add features like this to the docs. :)

**Comment by gionkunz** [comment]
Sure I will! :-) And thanks for your feedback! This will be in the advanced usage example of chartist.js. Generally the documentation is something I (who not?!?) need to catch up.

Btw. your issue made me notice that there is a possible bug and the dots are hidden behind the lines which should be the other way around I guess ;-)

**Comment by gionkunz** [comment]
I wanted to note on this issue that there is now full support for functionality like this with the new custom namespace attributes. Check the advanced example here http://gionkunz.github.io/chartist-js/getting-started.html#behavior-with-jquery

Cheers
Gion

**Comment by arechsteiner** [comment]
@gionkunz: Would you reconsider adding hover and tool tips to Chartist out of the box? I think it's an essential feature for charts displayed in the browser. I really like the approach you took using inline SVG and CSS and you've done a great job with the documentation (the live-edit code examples are something I will most definitely steal ;)

The only fly in the ointment is that tool tips on hover are not included. I think this might as well be the most popular chart library on GitHub otherwise.

Anyway just my two Rappen. Cool project either way.

**Comment by gionkunz** [comment]
Did you check the chartist tooltip plugin?

**Comment by arechsteiner** [comment]
Yes, I followed the link to the docs example but it seems broken:

![brokenchartisttooltip](https://cloud.githubusercontent.com/assets/1199486/15799647/95322aac-2a63-11e6-8cad-fb3e66792046.png)

Third-party plugins don't invoke a lot of trust and present an extra hurdle when getting started. That's why I would provide this functionality by default. Nothing against the plugin-approach for the more outlandish features. It keeps the code from bloating.
