### ISSUE TITLE
How to implement tool tips in the Line chart

### ISSUE THREAD

**Issue by Seishin** [chartist-js/chartist#47]
Hello!

I copy-pasted the LINE CHART WITH TOOLTIPS section example but the tooltips are not showing above the points as it's in the example. They're showing at the upper left corner without any style, just text.
jQuery and jQuery-ui are both included.

Any more dependencies?

Thanks!

**Comment by gionkunz** [comment]
Hi

The only thing to get this working is jQuery and only because it was the choice for the example. You could also use a different DOM library like $dom, MooTools or anything else.

For the specific example you only need jQuery and no jQuery UI.

The tooltips are not built into Chartist.js and currently you can only see the JavaScript code of the example. There is also a CSS part that you need to include in your code if you'd like to style your tooltip exactly the same. You can style the tooltip yourself or copy the styles with your browsers developer tools by inspection. The important part, and also why your tooltip has shown up at the same position always rather than moving with the pointer is that you need to set `position: absolute` on the .tooltip selector in your css.

Hope this helps.
Cheers
Gion

**Comment by Seishin** [comment]
Thank you very much! 
It really helped but it would be a good idea these little things to be explained in the documentation and examples sections.
