### ISSUE TITLE
Setting option "high" not working

### ISSUE THREAD

**Issue by ryanwalters** [chartist-js/chartist#474]
Is there a minimum value that must be set for the `high` setting to take effect?

http://codepen.io/ryanwalters/pen/MaJXGO?editors=101

In the example, I'm trying to set the value to 165, but the max value on the Y axis is still 200.

**Comment by jcdsr** [comment]
I have the same issue, don't know why it goes up to 200. Any ideas?

**Comment by jcdsr** [comment]
I think I found the solution:

axisY: {
  type: Chartist.FixedScaleAxis,  
  low: 0,
  high: 160,
  ticks: [0, 40, 80, 120, 160]
}

**Comment by wwalser** [comment]
For anyone else who comes here looking, the default axis drawing mechanism makes some trade offs affording for better drawing of ticks in exchange for precision of the `high` setting.

The maximum tick mark drawn for some numbers ends up being slightly above the number provided. If you're drawing charts using static data, providing your own tick marks using the `FixedScaleAxis` (as @carlosdv4 mentioned above) drawer may suit you better.

For details on the algo used, check out `getBounds` inside of core.js.

While I would have liked for this feature to be supported, my own reading of the code is that this is not a bug but expected behavior.

**Comment by gionkunz** [comment]
@wwalser is right. With `AutoScaleAxis` the high option is only considered a guidance but order of magnitude takes control after that. This behaviour is considered the "auto" within this axis. If you need exact dimension boundaries, you should use the `FixedScaleAxis`
