### ISSUE TITLE
Animation Broken with IE11

### ISSUE THREAD

**Issue by ayush** [chartist-js/chartist#486]
The `ANIMATING A DONUT WITH SVG.ANIMATE` example at https://gionkunz.github.io/chartist-js/examples.html is broken in IE. It appears like so:

<img width="988" alt="screen shot 2015-10-17 at 12 14 26 pm" src="https://cloud.githubusercontent.com/assets/188701/10560726/cadbb674-74c8-11e5-8178-bf3a3ef6f30f.png">

**Comment by JosefWN** [comment]
Expected behavior, the browser doesn't support those animations. Or are you referring to poor fallback (drawing nothing instead of drawing a chart without animations?).

See IE11: http://caniuse.com/#feat=svg-smil

Chrome has also deprecated SMIL, so I'm not sure it's viable to use it in the future.

**Comment by gionkunz** [comment]
@Puffton is right. SMIL animations don't work in IE at all. Check the compatibility table here: http://gionkunz.github.io/chartist-js/#browser-compatibility

In regards to SMIL please see #468

**Comment by ayush** [comment]
Thanks @Puffton / @gionkunz .

**Comment by gionkunz** [comment]
Sure, You should use animations with SMIL using progressive enhancement. You can use `chart.supportsAnimations` for conditionally add animations.
