### ISSUE TITLE
Place grid on top of chart

### ISSUE THREAD

**Issue by unhinged** [chartist-js/chartist#495]
I would like to have the grid lines appear over my bar and line charts. Is this functionality already baked in? If not, would it be possible to add it?

<img width="478" alt="screen shot 2015-10-27 at 3 57 44 pm" src="https://cloud.githubusercontent.com/assets/5385573/10770778/7f90f37a-7cc3-11e5-900d-77f4f45ae330.png">

**Comment by woble** [comment]
Since you can't control z-index of SVG elements in SVG 1.1 (SVG2 permits use of z-index), you have to rebuild the order programmatically as opposed to doing it through CSS.

You can write a plugin that does that. The following example is very crude (no check whether it's the right child, although by default grid, series and labels groups are in that order), but it should give you an idea of how to accomplish it.

``` js
(function(window, document, Chartist) {
    'use strict';

    Chartist.plugins = Chartist.plugins || {};
    Chartist.plugins.cgGridOnTop = function() {
        return function cgGridOnTop(chart) {
            if(chart instanceof Chartist.Line || Chartist.Bar) {
                chart.on('created', function() {
                    var layerGrid = chart.svg._node.children[0];
                    var lastChild = chart.svg._node.children[1];

                    lastChild.parentNode.insertBefore(layerGrid, lastChild.nextSibling);
                });
            }
        };
    };
}(window, document, Chartist));
```

**Comment by unhinged** [comment]
Thanks! I will plug this in and see if it works.

**Comment by gionkunz** [comment]
Cheers for the example @woble !
