### ISSUE TITLE
Guidelines for contribution

### ISSUE THREAD

**Issue by willsoto** [chartist-js/chartist#5]
This looks like a really promising project and I would like to contribute. 

Are there any coding standards, grunt tasks, tests, etc, that I should be thinking about?

I would gladly create a `CONTRIBUTING.md` file for others as well if you have any any specific criteria for contributing.

**Comment by gionkunz** [comment]
Hi paradox!

This is great! Thanks for picking this up! :-)

For a small library I already invested quite some effort in the dev stack. There is the build system, static site generator for the documentation site, documentation generation form JSDoc and much more. There is also a lot missing, especially proper testability of the different application parts, as well as tests, ci and code coverage reports.

Some starting points, things to be aware of which are not documented yet and my opinion on some stuff:
- Basically I'd appreciate a standard github flow where forks should be done on develop and requested to be merged with pull requests back to chartist-js/develop
- Core principles should be included again in the contribution guidelines
- For the styleguide I developed already something that I use in other projects. I'll include that as CODINGSTYLE.md and we can work on it to trim / slice / modify on demand.
- The .jshintrc provides the Chartist.js Formatting as well as validation rules
- There are basic grunt task
  - grunt build (creates the distribution of the example / demo site which is used as visual development help of the charts but also serves as the documentation site / gh-pages)
  - grunt serve (starts watch with livereload that is executing the same things as the site dist default task but for live development)
  - grunt test (executes jasmine tests separately, although we have a very big lack of tests :cry: )
  - grunt libdist (creates the libdist folder that contains UMDified, minified, and bannered versions of the concatenated files)
  - grunt serve:dist (executes a dist and serves the directory statically in order to serve with the production example / demo site)
- Generally we need to improve heavily on testability of the code and writing tests (I stared to write more tests with the SVG DOM manipulation component)
- Documentation: Everything is already in place and in the sitedist there is a apidoc folder generated that is generated by JSDoc generator. We should always use propper JSDoc comments on added code, even internal code, and at some point refactor the existing comments to JSDoc. For JSDoc it would be nice to create a theme / template at somepoint that matches the Chartist theme.
- The site documentation is built with Assemble.io. Generally a component based approach should be followed where there are already Handlebar partials / helpers in order to create whole sites based on components that can be specified by type and with their data in yaml files. This is kind of obvious when you start looking at the data files of getting-started for example but needs to be outlines somehow.
- The gh-pages branch has a different .gitignore and a script called ./doc-clean-pull.sh which is cleaning the gh-page and copy the sitedist content to the root folder. The procedure to build chartist.js site documentation (gh-pages) is "grunt && git checkout gh-pages && ./doc-clean-pull.sh" followed by a commit and push but I think this procedure will currently be kept in the responsibility of the core contributors

There is actually much more that I had in mind but I hope this is a good starting point. Also we can add other ideas and debate on different opinions of course.

Cheers and your contribution is much appreciated!
Gion
