### ISSUE TITLE
Chart redraw on container resize

### ISSUE THREAD

**Issue by adstep** [chartist-js/chartist#512]
I understand that on the window.resize event that chart redraws itself. I was wondering what the best way to do the same when the chart's container div changes size?

**Comment by coltonmccormack** [comment]
Unfortunately, doing this type of thing usually requires periodically polling the element and getting it's height/width, comparing against the last known height/width, and redrawing if they are different.

In the future, hopefully [DOM Mutation Observers](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) will help out with making this event based rather than cyclically dirty-checking it as I mentioned above.

**Comment by gionkunz** [comment]
@thatguyyoulove is right on this, we'll need to wait for mutation observers

**Comment by inthenameofmusik** [comment]
@thatguyyoulove what would be the proper way to manually poll the element? I have no problem doing it this way, but are you suggesting manually adjusting the `width` and `height` properties of the chart? Or somehow telling the chart to look at the parent element's dimensions again?

**Comment by Kiruwagaka** [comment]
@gionkunz https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver seem to be working on every modern browser, will we be seeing this update any time soon?

**Comment by EliasAhlers** [comment]
Anything new regarding this? Would like to have it 👍

**Comment by KoanLeeroy** [comment]
I do something like this:

```javascript
import ResizeSensor from "css-element-queries/src/ResizeSensor";

export default class ChartResize {
    public static init() {
        window.onload = () => {
            const charts = document.querySelectorAll(".ct-chart");
            charts.forEach(chart => {
                new ResizeSensor(chart, () => {
                    // resize chart
                    console.log("Resizing chart");
                    window.dispatchEvent(new Event('resize'));
                });
            });
        }
    }
}
```
