### ISSUE TITLE
why not using "switch"?

### ISSUE THREAD

**Issue by tao1587** [chartist-js/chartist#519]
SWITCH CASE  can avoid write too much IF ELSE ?

you didn't  say any more

**Comment by gionkunz** [comment]
I consider switch case as a bad practice because it's very error prone. You can miss break statements, create block context's or don't (can become an issue when using block scope variables with const / let) and it's generally not so easy to reason about as it's not very explicit.

Consider the following code:

``` javascript
switch (expr) {
  case "Oranges":
    console.log("Oranges are $0.59 a pound.");
    break;
  case "Apples":
    console.log("Apples are $0.32 a pound.");
    break;
  case "Bananas": {
    console.log("Bananas are $0.48 a pound.");
    break;
  }
  case "Cherries":
    console.log("Cherries are $3.00 a pound.");
    break;
  case "Mangoes":
  case "Papayas":
    console.log("Mangoes and papayas are $2.79 a pound.");
    break;
  default:
    console.log("Sorry, we are out of " + expr + ".");
}
```

There are so many things that could be wrong with this code and it's not very explicit. Did I miss the break statement in Mangoes or is it meant to be combined with Papayas? Was this an error or as designed? Did I include a default statement or missed it? Was it an error or as designed? Switch case is also the only formatting context that does not require blocks to execute certain code areas, which is very messy in my opinion.

You can see that there are just too many paces where the code is not explicit, messy and unclear. If we write the above with if / else, we might have a bit more code, but it's definitely a much better structure and more robust code.

``` javascript
if (expr === "Oranges") {
  console.log("Oranges are $0.59 a pound.");
} else if (expr === "Apples") {
  console.log("Apples are $0.32 a pound.");
} else if (expr === "Bananas") {
  console.log("Bananas are $0.48 a pound.");
} else if (expr === "Cherries") {
  console.log("Cherries are $3.00 a pound.");
} else if (expr === "Mangoes" || expr === "Papayas") {
  console.log("Mangoes and papayas are $2.79 a pound.");
} else {
  console.log("Sorry, we are out of " + expr + ".");
}
```

I generally dismiss swich / case and I never recommend it to any developers or my students. It's a legacy construct that found it's way in way too many programming languages, but should be dismissed in my view.
