### ISSUE TITLE
optionsChanged event never emitted

### ISSUE THREAD

**Issue by ghost** [chartist-js/chartist#525]
The 'optionsChanged' event is never emitted when a chart changes due to media query config being applied. This is because in Chartist.optionsProvider, the function updateCurrentOptions expects to be passed an optional boolean, but in fact when called from a media query listener, it is passed an event object, therefore tripping over the event emit guard.

I have the following fix:

https://github.com/BlackPepperSoftware/chartist-js/commit/2e3685ca06b6aa681c559f74841d627902d59184

But I couldn't get the project to build owing to libsass / node-sass errors, so I haven't submitted a pull request.

**Comment by stringfellow** [comment]
I think this is still a problem - adding the following never results in a console message when resizing the browser window (the chart changes to the responsive options though):

```
myChart.on('optionsChanged', function() {
      console.log('Changed');
});
```

I need a way to detect that the mode has changed so that I can reorder the data (the reverse option does not do what I need unfortunately).

**Comment by stringfellow** [comment]
_bump_ Is there any chance of responding to this issue or incorporating the fix pls, @gionkunz  😇
