### ISSUE TITLE
Gauge chart not really round

### ISSUE THREAD

**Issue by SekibOmazic** [chartist-js/chartist#55]
Just look at the attached image (black slice, inner circle). This effect is on Chrome/MacOS only. No problems on FF/Windows.

![gauge-chrome-macos](https://cloud.githubusercontent.com/assets/3735902/4438933/58314d9e-47b2-11e4-9444-8c2d665a45b3.png)

**Comment by SekibOmazic** [comment]
Maybe it is safer (more browser independent) if you draw the arcs (doughnut slices) like this:
M x0 y0 
A  ro ro 0 largeArcFlag 1  x1 y1
L x2 y2
A ri ri 0 largeArcFlag 0  x3 y3
Z

with 
(x0,y0) - starting point on outer circle, 
(x1,y1) - endpoint on outer circle, 
(x2,y2) - endpoint on inner circle,
(x3,y3) - startpoint on inner circle
ri - inner circle radius
ro - outer circle radius

**Comment by SekibOmazic** [comment]
BTW - good job!

**Comment by gionkunz** [comment]
@SekibOmazic Thanks for the issue! I've noticed this also and it's a drawing problem in chrome. The thing why I wanted to stick to a simple stroke for the donut / gauge charts is the flexibility you have in styling it with CSS. You can customize the stroke width, strike cap etc with CSS which is a great separation of concern. I've also thought about changing to drawing a shape but then the problem is that you'll need to configure all this in JavaScript which breaks the basic idea of chartist. Let's track this here and see where it goes.

**Comment by lyubarskiy** [comment]
I have the same problem on Chrome/Windows (

**Comment by gionkunz** [comment]
I'm closing this issue for now. We'll anyway provide a solid option for donut / pie charts which will solve this issue. By implementing #330 properly we can solve this.
