### ISSUE TITLE
In the documentation: Cannot set height as a string–doesn't render

### ISSUE THREAD

**Issue by RVMendoza** [chartist-js/chartist#58]
When I tried to set a height as '100px' or '50%' it goes all cray cray and doesn't render.  If I just do straight up `height: 400` with no quotes or px, it works, but now we're stuck with pixels which is a problem with fluid design.

Try this:

``` html
// Specify a fixed height for the chart as a string (i.e. '100px' or '50%')
  height: '50%'
```

![image](https://cloud.githubusercontent.com/assets/4342363/4492819/6f4380da-4a44-11e4-99ef-f14f6c5eceaf.png)

**Comment by gionkunz** [comment]
Hi there,

Thanks for reporting this issue. I think this was more of an edge case for me till now, as I'm really suggesting to use a container for chartist and don't set a width / height in the configuration. But as this is possible we should invest some time to make this more robust.

Cheers
Gion

**Comment by SekibOmazic** [comment]
Have the same issue.
@gionkunz btw, what ist the "proper" way to have the chart taking 100% width and 100% height of parent container? In my code it seems that only width is responsive. Do I need preserveAspectRatio on the svg?

**Comment by gionkunz** [comment]
@SekibOmazic Chartist creates an SVG object inside of a container element. The container can be of any type but should be a block / inline-block with position relative. By default if you initialize Chartist without width / height parameters, it will use 100% for both. The Chartist CSS is providing some container classes that will help you creating responsive / scalable container elements. You should read this chapter: https://gionkunz.github.io/chartist-js/getting-started.html#as-simple-as-it-can-get

preserveAspectRatio is not really needed as Chartist is re-drawing the chart to fit your container and does not scale it's content.

It's recommended to always use an aspect ratio container as described in the getting started documentation rather than using the width and height parameters of the chart. They are only there if you'd like to use absolute height and width and currently only pixel are supported and need to be passed as numbers (This is what we should change with a enhancement).

**Comment by gionkunz** [comment]
Also I'm using a special form of a responsive / aspect ratio container that is making use of pseudo elements to expand the container. Usually what you see is that a padding-bottom with percentage is used on the container directly. The problem with that is that padding-bottom / padding-top are relying on the _parents width_ to calculate the values. And with the standard approach you'll need to use an other wrapper if you'd like to set a width on your container. Otherwise the padding with percentage doesn't work correctly. Chartist uses a child pseudo element in the container to make it scale that has no width and height but padding and also floats. That way you can specify any width on your container and it still works as expected. You can check out this code pen: http://codepen.io/gionkunz/pen/iJItx

**Comment by SekibOmazic** [comment]
@gionkunz Thanks for your answer(s). I'll have to analyze you code pen and maybe "borrow" some css. It seems that I have an issue with my styles.

**Comment by gionkunz** [comment]
Hi Guys this is fixed in the latest version 0.2.1. It's now possible to pass any CSS length (px, em, rem, cm, vw ....) and Chartist will render the SVG correctly. If a number is passed then pixel is assumed. This is effecting also situations where you draw a Chartist Chart inside of SVG DOM (which is whats happening on the Chartist documentation landing page) where there only pixels are supported.

**Comment by SekibOmazic** [comment]
@gionkunz Sorry if this is not a proper place to ask a question, but I still have a problem with creating "responsive" line charts. What I want to achieve is a line chart that occupies whole parent div like this (made with D3): http://plnkr.co/edit/jw9WXGn76gjDPoQTLq9m?p=preview (try resizing window)

What I got so far: http://plnkr.co/edit/zJuFLVDvA0WYuFit3lGd?p=preview

It's obvious that an aspect ratio container is not a way to take, so I tried with the options (setting width and height) but it won't work for some reason.

**Comment by gionkunz** [comment]
Are you sure this example should work? You're including from raw.github which is no longer supported as they send it as plain text on purpose. You can use jsDelivr CDN for the latest Chartist version.

Why do you think an aspect ratio container is not a way to take? This is the recommended way to make block content responsive.

Here is your code that works with the golden section aspect ratio container: 
http://plnkr.co/edit/FtHxLlgCJxu6bhrZk29k?p=preview

Here is a variation that does not use a aspect ratio container but fixed dimensions:
http://plnkr.co/edit/oOvVYI6d483IxZgPrCcw?p=preview

Just set the width to 100% and height to anything you want. You could also specify 100% width and 100% height to fill the whole parent.

**Comment by SekibOmazic** [comment]
@gionkunz OMG - it works ( http://plnkr.co/edit/V7PyHOWtavhIA4QO9N5f?p=preview ).
Thanks a lot. The trick was to explicitly tell container to take 100% height. 

There is one small issue: it seems that chartist "adds" 5px to the height. Maybe it is a plunker issue - need to investigate.

Now I can get rid of D3 und use chartist in our product (teamgeist.io) as soon as we get stacked bar chart ;-)

**Comment by SekibOmazic** [comment]
@gionkunz Would you mind if I send you a question via Email? It's about SVG and github is not the right platform for that. No problem if you don't have time for this ;-)

**Comment by gionkunz** [comment]
Sure drop me a mail! It's gion.kunz@gmail.com
