### ISSUE TITLE
Width and height not working in Firefox

### ISSUE THREAD

**Issue by albertolopez** [chartist-js/chartist#592]
When setting width and/or height in the options of any chart, the chart is cropped but not resized.

I am using Firefox 43.0.4

![chartist - examples 2016-01-22 10-26-39](https://cloud.githubusercontent.com/assets/309681/12506924/ac7ef864-c0f2-11e5-87a0-a31a46f36f4e.png)

The code is the one in the examples, I have tried with different chart types and all fail

``` javascript
var data = {
  series: [5, 3, 4]
};

var sum = function(a, b) { return a + b };

new Chartist.Pie('.ct-chart', data, {
  width: 300,
  height: 300,
  labelInterpolationFnc: function(value) {
    return Math.round(value / data.series.reduce(sum) * 100) + '%';
  }
});
```

**Comment by gionkunz** [comment]
Hi there. The problem boils down to the width and height estimations within the Svg DOM builder of Chartist which is rather complex. We included a workaround for getting around this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=530985

However, the bug is long fixed and we should be fine by just relying on `getBoundingClientRect`. I think IE9 should also be fine with it.

I guess https://github.com/gionkunz/chartist-js/blob/develop/src/scripts/svg.js#L338-L351 can be simplified by just using `this._node.getBoundingClientRect().width` and `height`. Also the fallback to `getBBox()` can be removed I guess.

I'll flag this as a bug but happy if someone could pick this up and make a PR. I guess testing in browsers >1%, -IE8, +IE9 would need to be done extensively.

**Comment by gionkunz** [comment]
For now, as the fallback that will be used in Firefox is the width and height of the parent element, just make sure you also have a parent element (the container of the SVG) that holds the desired dimensions.

**Comment by gionkunz** [comment]
I've tested IE9, IE10, Safari 7.1, Firefox, Chrome and Android and going with `getBoundingClientRect` without any fallback does the job. I'll make a quick fix for this.

**Comment by NoBodyButMe** [comment]
Hello

I'm sorry to ask, but is this bug already fixed in the release? I tried to use it but still have the same problem in Firefox.
