### ISSUE TITLE
Changing padding with plugin

### ISSUE THREAD

**Issue by nhagen** [chartist-js/chartist#595]
I'm writing my own horizontal legend plugin which injects under the x axis and wraps the keys to new rows when necessary. Its not clear if there is a way to increase the padding below the x-axis dynamically depending on how much space I need.

Is there a way to update the padding under the x axis to make room once the legend knows how much height it needs?

**Comment by gionkunz** [comment]
That will be tricky as it's kind of a chicken egg problem. If a plugin updates the chart it will cause a complete redraw which is again causing the plugin to re-render causing an infinite loop I guess. Except you can design your plugin that it will not cause a chart update if the space calculated is fitting because of the first re-draw. You can use `chart.update` to update any options.

**Comment by gionkunz** [comment]
We should consider this when working on #810
