### ISSUE TITLE
License change?

### ISSUE THREAD

**Issue by shyndman** [chartist-js/chartist#604]
Hey @gionkunz,

First off, nice work on the library. Looks great.

I was wondering if you would consider changing the license (or dual licensing) to a better-recognized permissive license (Apache 2, MIT, BSD). wtfpl isn't allowed at Google, unfortunately.

**Comment by mcdonnelldean** [comment]
I was just about to ask this. I appreciate the intent but trying to get this past legal could be a nightmare. Could you possibly go with MIT? It's essentially the same License in spirit and will give everyone who has to run things through legal a green light.

I'd be super happy to PR this for ye if time is an issue.

**Comment by mcdonnelldean** [comment]
I would like to note the irony of me being able to just fork and change this because I can 'Do whatever the fuck I want' is not lost on me :D

**Comment by gionkunz** [comment]
@mcdonnelldean you got the point :-)

**Comment by mcdonnelldean** [comment]
@gionkunz Does that mean your not open to changing the license?

**Comment by gionkunz** [comment]
Well, I tried to avoid changing the license as I really see no reason why companies should abandon the license. Still I had so many requests for this from large companies that I feel it's probably a better idea to change. Just so developers at large companies can use Chartist if they desire. 

I still would like to keep the WTFPL as a statement of freedom within the library. I'm open to a multi licensing / dual licensing https://en.wikipedia.org/wiki/Multi-licensing, and since WTFPL is GPL compatible it shouldn't be a problem offering WTFPL and MIT and give the user the choice which one to use.

**Comment by mcdonnelldean** [comment]
@gionkunz I think that's a fair compromise. I appreciate the aspirational nature of the WTFPL.

**Comment by gionkunz** [comment]
I switched to dual licensing WTFPL and MIT within Chartist 0.9.6 :smile: :+1:
