### ISSUE TITLE
Donuts and well, data with the value of '0'

### ISSUE THREAD

**Issue by rstudner** [chartist-js/chartist#606]
![screen shot 2016-02-04 at 2 49 38 pm](https://cloud.githubusercontent.com/assets/209970/12827610/8c0c48dc-cb4e-11e5-9b7d-4fe8e187c134.png)

Now, of course I can handle all this lah lah.

Just curious if there is a reason the library fires up a bunch of console errors (versus something prettier).

This isn't a big deal, just trying to dip my toe into maybe working on this project :).

**Comment by gionkunz** [comment]
Verbose error handling can easily take up 20% of a libraries size. I'd like to either figure out how we can do verbose error handling in a more aspect oriented way so that we can create a dev bundle that contains verbose error messages and a production bundle that does not have verbose error handling. So far I tried to avoid verbose error handling at all :-) and it wans't such a huge issue. We are developers and should be able to backtrack an error very quickly. If not, we should learn the skill to do so ;-) I understand it would be developer friendlier to have verbose error messages but not at the price of library size. We could also prioritize the errors and only be verbose at the important ones. Or we build a system that handles errors with a pluggable assertion or more in an aspect oriented way so it's not directly included in the code and can be excluded for a prod bundle.

**Comment by gionkunz** [comment]
We should consider this in #811
