### ISSUE TITLE
Override Donut Value Objects in Series Array

### ISSUE THREAD

**Issue by johndturn** [chartist-js/chartist#640]
I'm attempting to add a custom class to each series passed into a Donut chart. According to the API docs this should be easy: 

> The series property can also be an array of value objects that contain a value property and a className property to override the CSS class name for the series group.

The docs provide an example of this: 

![screen shot 2016-03-16 at 5 04 29 pm](https://cloud.githubusercontent.com/assets/10634270/13831416/3825618e-eb99-11e5-9407-4701dd107dfc.png)

Sadly, I can't seem to get this to work. The SVG loads into the DOM, but the actual values don't show up. It's as if I passed no values at all to the chart. I've experimented with removing object keys, changing values, and other things as well. The only thing that gets the donut to render is if I only pass in numbers to the `series` array. Is this a bug, or is this just a user error on my part? 

I've even attempted to copy and paste in the sample code from the API, and it appears that the normal pie chart renders decently. But, when I add the `donut: true`, the chart breaks. 

Here's my code:

![screen shot 2016-03-16 at 5 04 44 pm](https://cloud.githubusercontent.com/assets/10634270/13831421/3e9be952-eb99-11e5-9c72-5b9a18298ad6.png)

**Comment by jessewilliams1** [comment]
I'm seeing the exact same issue...
What I'm trying to do is create a custom "Power meter" of sorts:
<img width="823" alt="screen shot 2016-09-06 at 9 57 16 pm" src="https://cloud.githubusercontent.com/assets/1137717/18300457/18c22f70-747e-11e6-8eb6-fc9e3ba4f731.png">

I really needed this functionality though so I ended up brute-forcing a solution...
I set the .ct-series-b class to always be gray:

`.ct-series-b .ct-slice-donut {
    stroke: #f3f5f6;
}`

Then, i change the series-a manually depending on value:

![screen shot 2016-09-06 at 10 04 57 pm](https://cloud.githubusercontent.com/assets/1137717/18300459/24147626-747e-11e6-8c1b-b8cc598d70fe.png)

Not the prettiest but I hope it helps you until there's a fix!
(or maybe one of these day's I'll dig into it and help out)

**Comment by gionkunz** [comment]
Hi there. There's nothing wrong with Chartist here. Since the donut is using unclosed paths to render, you need to use `stroke` to color your donut slices instead of `fill`. A quick look at the default styles helps. Also reading the getting started guide on styling your chart (the donut section) should give you the necessary clues. http://gionkunz.github.io/chartist-js/getting-started.html#customizing-the-default-css.

Here's an example: http://jsbin.com/yuqides/edit?html,css,js,output

Please tell me if you think we can improve the documentation on this.

Cheers
Gion

**Comment by johndturn** [comment]
Perfect, thanks!
