### ISSUE TITLE
Label value near bar ( on top if the bar are vertical, right if they are horizontal ): how?

### ISSUE THREAD

**Issue by biapar** [chartist-js/chartist#662]
Label value near bar ( on top if the bar are vertical, right if they are horizontal ): how?

**Comment by Martinomagnifico** [comment]
I started out with this issue: https://github.com/gionkunz/chartist-js/issues/281

And made a plug-in out of it: https://codepen.io/martino/pen/mVgyOZ

**Comment by Martinomagnifico** [comment]
Actually I prefer getting the prefix and suffix from the html placement, in a data-attribute like data-chart-prefix. But that has nothing to do with the label placement, although it mixes because labels use those prefixes. Even better would be something like a whole dynamic label as a data-attribute.

**Comment by gionkunz** [comment]
There's also this plugin: https://github.com/Remco75/chartist-plugin-barlabels

**Comment by zanechua** [comment]
@Martinomagnifico you should make it into a plugin.

@gionkunz That doesn't work properly versus the one @Martinomagnifico posted.

**Comment by gionkunz** [comment]
I leave it up to you guys, use @Martinomagnifico s snippet or make it into a plugin
