### ISSUE TITLE
Info on browser support?

### ISSUE THREAD

**Issue by benseven** [chartist-js/chartist#67]
Hi guys,

Chartist looks great - could I suggest that if you have information on browser support, you publish it on the site? It's the first thing we were looking for as part of the decision whether to use it or not!

Thanks,

Ben

**Comment by gionkunz** [comment]
Yeah! :-) It worries me that youre the first one who asks! :-) I've got the desired compatibility table somewhere as i prepared it sometime ago. We should put that onto the landing page somewhere with some icons or so. Im also not sure if we still comply with all the browsers that were in scope at the start because we added a lot of stuff and our automated tests are very poor atm. In short: major browsers & IE9+ & android 4+

**Comment by benseven** [comment]
Thanks!

**Comment by wescosta** [comment]
Are there polyfills to make Chartist work on IE8 ?

**Comment by gionkunz** [comment]
No :-) IE8 must die. It was a great time and we all got paid double rates because of it but now its time to say good bye :-) there are things like svg2vml or you could have a server with phantomjs that is rendering an image, caches it and exposes it for client request or just make a png for the charts as fallbacks :-) But i really dont support any of those things. If you really need to display interactive content in IE8 then you should consider a library that is built for this massive split like highcharts which uses different rendering engines based on VML.

**Comment by wescosta** [comment]
Agree with you. IE8 must die! I think I got robbed. I did not get paid double rates to support IE8. haha
Thank you for your quick answer!

**Comment by F1LT3R** [comment]
Just wanted to clarify whether IE9 Support is official and ongoing for the duration that Microsoft supports IE9?

**Comment by gionkunz** [comment]
There is livelong support for IE9 with the current version of Chartist. There is no guarantee that upcoming versions of Chartist will still support IE9. The first major release Chartist 1.x will likely support IE9 but there is no guarantee that any further major version will support IE9, even if this happens before Microsoft stops support of IE9. I can also guarantee that there will be no minor release that breaks IE9 support so only a major release will potentially break the support.
