### ISSUE TITLE
Unable to add event listener to pie chart segment

### ISSUE THREAD

**Issue by gsnedders** [chartist-js/chartist#684]
I want to add a mouseover event listener to a pie chart segment; I thought I'd be able to do this on chartist's draw event, but the `e.element` points to an object whose prototype is `Chartist.Svg`, and that exposes no way I can see to add an event to the element without using its presumably internal `_node` property.

It would be nice to expose the actual DOM node somehow, or at least make it possible to add/remove event listeners.

**Comment by pareznik** [comment]
Confirming this, same problem with onClick / onMouseUp. I was unable to find a simple way to add individual events to each pie chart segment.

**Comment by gionkunz** [comment]
The easiest way is to use event delegation. Vanilla JS being a bit complex if you'd like to stay cross-browser compatible. If you're using jQuery then simply registering your event listener with delegation on your container does the job very well.

``` javascript
$('.container').on('click', '.ct-point', function(){});
```

Using `_node` is fine, actually it's hidden because you can break the SVG API if you overwrite the value. However, reading is perfectly fine. We should add a "public" method though. I'll open a task for that.

**Comment by gionkunz** [comment]
Well, let's use this ticket to track this. Adding a public `getNode` method would be appreciated.

**Comment by gionkunz** [comment]
@gsnedders got time for a PR? :-)

**Comment by gsnedders** [comment]
@gionkunz I'll pick it up when I'm back from holiday if nobody's done it before. :)

One thought, though—doesn't the animation function (I forget what it's called but hey, I'm on holiday) rewrite it, replacing it? (I could well be forgetting what I found when I looked last week.)

**Comment by oshingc** [comment]
This wasn't resolved? : O

**Comment by gsnedders** [comment]
I entirely forgot about this. Turns out being on holiday doesn't help me remember. :)

**Comment by gionkunz** [comment]
Hehe :-) I've opened a different issue for tracking this effort #812
