### ISSUE TITLE
Unexpected behaviour when drawing a graph that is based on a data array with some null values

### ISSUE THREAD

**Issue by ghost** [chartist-js/chartist#689]
**Example 1:**
The data array has no "null" values. However, there are some "0" values:

```
var chart = new Chartist.Line('.ct-chart', {
   labels: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
   series: [[3, 2, 0, 5, 0, 6, 9]]
}, {
   lineSmooth: Chartist.Interpolation.step({
     postpone: true,
     fillHoles: false
  }),
  showLine: false,
  showArea: true,
  fullWidth: true,
  low: 0
});
```

The resulting graph looks like this:
<img width="1141" alt="ex1graph" src="https://cloud.githubusercontent.com/assets/19173470/14994226/f9ba98c8-116e-11e6-87a1-59a4b61824ac.png">

**Example 2:**
The data array has some "null" values, instead of "0":

```
var chart = new Chartist.Line('.ct-chart', {
   labels: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
   series: [[3, 2, null, 5, null, 6, 9]]
}, {
   lineSmooth: Chartist.Interpolation.step({
     postpone: true,
     fillHoles: false
  }),
  showLine: false,
  showArea: true,
  fullWidth: true,
  low: 0
});
```

The resulting graph looks like this:
<img width="1139" alt="ex2graph" src="https://cloud.githubusercontent.com/assets/19173470/14994279/49ecdeaa-116f-11e6-980d-d8835975b5f7.png">

In my opinion, the second example is **not** the expected result when having such a data array. I mean, there is clearly a value (= 2) for "Tuesday" and (= 5) for "Thursday", so why are they not visible as they are in the first example? Is this a bug or am I doing something wrong? I taught chartist can handle "holes in data", but in this case it makes even a bigger hole compared to the existing ones. I would like to have the behaviour of the first example without having to replace all "null" values with "0", as they have different meanings in my use case.

Thank you in advance for your help.

**PS**: These charts have been made with the current release of chartist **(v0.9.7)**

**Comment by gionkunz** [comment]
The problem is that a single point within a line chart with holes has no solid surface nor a line. Its just a point. Turn on show point to see what I mean. Youre using the line chart with step interpolation to achiev a bar chart look. Whats the reason why youre not using a bar chart in the first place?

**Comment by ghost** [comment]
I know what you mean... In this quick example I did not set showPoint to "true". However, in my use cases it is set to "true", but with an opacity of "0". This is because I only need them to show a tooltip, which otherwise will not appear, if showPoint is set to "false". Anyway, this is not the problem. The problem is, that the step interpolation draws additional points in order to show an area between the points based on the data and the additionally created points - BUT in case of the second example, this is not done. The resulting graph is ambigious, because a single value can not only be represented by an area, but also by a point. How do you justify two different representation types for a value in the same graph, with the same interpolation, and the same underlying data? Why should someone use this interpolation type, if a single visible point representing a value is already enough?

To answer your question: the reason I am not using a bar chart is because I need a graph that represents a gapless area for each data stream in the graph, which is dynamically scalable, no matter how many datapoints it containts. Gaps should only be displayed in case of "null" or "0" values. I first tried to achieve this with a bar chart, but the problem was, that it was kind of impossible to make the bars touch, but not overlap each other. The bars were either too far away from each other, or that close, that they were overlapping each other.
Thats why I am using the line chart with the step interpolation. It looks like a bar chart, where one bar is attached with the bar on the left / right, so that they represent an area - it's exactly what I need. But now I faced this issue, which simply doesn't visualize the underlying data as it really is...

**Comment by fil-pit** [comment]
Hello everybody,
I have come across the same problem, which indeed, seems more like a bug, than an unofficial feature or something like that. This is my explenation: There can be no "step", for the purpose of this interpolation, if an additional point is not created. I guess, this is the reason why the documentation says that this interpolation creates extra points. If this is not always done, someone can not rely on chartist to visualise the data correctly with this kind of interpolation.
In other words, a value should never have influence on the visualisation of another value, because it stands for itself. The values may have a mathematical or any another semantic dependency, but from the visualisation's perspective, they are completely independent from each other. Therefore, in order to draw value B, it should never matter what value A, C or any other value than B, is. The library should simply draw value B like every other value, with two points, in order to connect them horizontally. In the end, it should not matter at all, if someone decides to show only points, a line or an area, as long as every value is drawn always the same way. Therefore I would say, that the expected result of the second example should also be the graph of the first example.

**Comment by gionkunz** [comment]
Well, it's a line chart and the semantics of a line chart are clearly point to point line. Step interpolation is just a filter of this representation and the above result is a consequence of both. For a use-case like this I'd really use a bar chart because that's the correct semantics for the desired visualization.

**Comment by gionkunz** [comment]
Closing this issue now, please feel free to re-open or further discuss
