### ISSUE TITLE
Synchronously render chart.

### ISSUE THREAD

**Issue by DylanPiercey** [chartist-js/chartist#690]
I am trying to build a server side version of chartist that renders xml vs dom for use in isomorphic react applications.

I have everything setup with a lightweight virtual dom and I can create the svg string but the main issue I have is that the api is forced to be async.

``` js
// Must wait for chart to be created (async) to pull out svg string.
chart.on('created', function () {
  ...
})
```

Is there a way to force chartist to render synchronously?

**Comment by gionkunz** [comment]
I was thinking about this a lot in the past. The main reason why we're deferring initialization through the event loop was to allow registration of event handlers in the same call-stack when creating the chart instance. Unfortunately it's not possible to create the chart synchronously at the moment since the initialize function in Base.js is closure scoped and not exposed.

We will reconsider this and maybe provide a sync option or even get rid of the constructor based initialization and force something like `new Chartist().on().on().render()`. This is covered by #813 which will be part of our 1.0 work.

**Comment by NeomMob** [comment]
Hi,
I am also in the need to have a synchronous rendering. Until it is developped in version 1.0, is there any workaround that can be used to achieve a similar result?

Thanks for your help and this awesome library!
