### ISSUE TITLE
Return values for chart constructors

### ISSUE THREAD

**Issue by willsoto** [chartist-js/chartist#70]
Would it be possible to return some sort of chart object that contains information related to the newly constructed chart?

For example, return the final values for the config objects that were passed in once they are merged with the defaults.

A little context for why I feel this would be good for 3rd party libs (and to make sure I'm not falling victim to the [XY problem](http://meta.stackexchange.com/a/66378)):

I am trying to find a way to handle events (e.g., click, mouseover, etc) in an angular way. The best way to do this, I think, would be as you suggested in #36 ([comment](https://github.com/gionkunz/chartist-js/issues/36#issuecomment-55454870)), which is to use nested directives. If I were to go this route, it would require a lot more effort, but it would be the **right** way to go. I may explore this in a branch and get your feedback...perhaps this can be a dual endeavor. I would want to do this in such a way though that the entire library is not being re-written.

The other option is get the relevant elements and attach emitters (maybe, still working through this). But this presents it's own problems in that the class names can be changed by the user and I don't want to have logic in the directive to figure out whether or not this happened. This means that the directive would have to maintain knowledge about the default values, and if they change then I'd have to update the wrapper, etc. I'd rather just read off the final value from the config object. 

Do you have any thoughts on this? I'm open to suggestions on the best way to get this done.

Thanks!

**Comment by gionkunz** [comment]
Hey Will

I get the idea and thanks for explaining with so much detail. There are just custom events in Chartist where they are actually needed, or in other words, where you don't have events already by the standard (matchMedia, DOM events etc). This means for click, hover etc. we should also leverage the DOM events in ng-chartist.js. For all events that can only come from Chartist we have the EventEmitter inside of chartist to which you can bind using the `on` function. For the current options there is the `optionsChanged` event you can use. Its emitted here: https://github.com/gionkunz/chartist-js/blob/develop/source/scripts/chartist.core.js#L596-L599 This event is also re-emitted if the options change due to the media query listeners and the override mechanism in Chartist. The problem currently is that Chartist does the first draw and initialization when you create the Chart with the "constructor" function. By then it's already too late to listen for any events. For this purpose I was moving the initial `createChart` call into a setTimeout so it performs sometime after the current call stack finished which gives you the possibility to register for draw events right after you created the chart and they will be triggered. The "problem" currently is that the `optionsProvider` is initialized still in the call stack where you initialize the chart. https://github.com/gionkunz/chartist-js/blob/develop/source/scripts/chartist.line.js#L384-L389

We would just need to move the `optionsProvider` initialization into the `setTimeout` just before the call to create the chart. This would then also allow you register for `optionsChanged` just after you created a chart (like this http://jsbin.com/gutey/1/edit which currently only works for subsequent option changes, try resize the window)

If you create a pull request for this for chartist line, bar and pie, that would be awesome! I'll soon create a base chart prototype which will contain all the code that is currently just duplicate code in the individual files, but for now we could just move the `optionsProvider` initialization as a quick win.

Cheers
Gion

**Comment by willsoto** [comment]
I've thought on this a bit and your suggestion would work for my needs. It would be nice to have it be part of the return object as well from the constructor, but this will do :stuck_out_tongue: 

I created a PR with the requested changes. It felt a bit easy, so I'm not sure I understood correctly. Let me know if those are the changes you wanted.

edit: Also something that I would like to discuss is the updating of charts with streaming data - like the example you added in ng-chartist.

Currently, the chart is **recreated** when the data changes, meaning all handlers are lost and thus have to be rebound. In my opinion, there should be a better way to handle data updates. Having to recreate the chart every time is resource intensive...especially if you have a lot of charts on the page. 

Do you think this would be worth discussing, perhaps in another issue?

**Comment by gionkunz** [comment]
The merge request should be fine. From my guts feeling i think the change is fine :-) ill test it tomorrow on the dev branch. If there is an issue we can fix it on the dev branch. Now you should be able to register an even handler for optionsChanged right after the chart creation and catch the first configuration.

The stuff youre talking about is next on my list! Its actually issue nr #3 :-) we should start this and let it be part of chartist 1.0.0 . Base chart prototype should also be part of this. Ill create a milestone for this tomorrow.

**Comment by gionkunz** [comment]
Can we close this issue?

**Comment by willsoto** [comment]
Yup. Excited to see what's planned.
