### ISSUE TITLE
Line graph line goes below bottom y-axis

### ISSUE THREAD

**Issue by dodozhang21** [chartist-js/chartist#720]
See this example.

http://codepen.io/dodozhang21/pen/dXXOVv

When the line is made thick, it goes below the bottom y-axis and covers up x-axis labels.

Anyone has any idea to address this issue?

**Comment by gionkunz** [comment]
That's due to the artifacts cardinal interpolation can cause on large value changes. You can switch to simple interpolation or the newly added cubic interpolation in version 0.9.8. http://gionkunz.github.io/chartist-js/examples.html#example-line-simple-smoothing

In 0.9.8 cubic is the standard interpolation for smoothed lines.

I'll close this issue, feel free to ask if something is still unclear.

Cheers
Gion
