### ISSUE TITLE
Distance Between Bars

### ISSUE THREAD

**Issue by Zaid-Mirza** [chartist-js/chartist#748]
Scenaria is,

I have drawn a bar chart, after setting srtoke-width:30px. Bar chat looks strange. 
![bar](https://cloud.githubusercontent.com/assets/13308482/17192604/b411195e-5468-11e6-9493-767d5803e421.jpg)

I want distance between bars  I used seriesBarDistance but its not working as below code
`var barchart = new Chartist.Bar('#barchart', data, { distributeSeries: true }, {

```
         seriesBarDistance:20,
         axisX: {
             // On the x-axis start means top and end means bottom
             position: 'start'
         },
         axisY: {
             // On the y-axis start means left and end means right
             position: 'start',
             onlyInteger: true,



         }
     });`
```

and one more think labels are placed at the end of cell. I want them in Middle. Thanks in Advance

**Comment by metodribic** [comment]
I believe this is because seriesBarDistance is mesured from center of one bar to next one and yours is set to 20 but your bar width is set to 30 and this is why they overlap. Set them to be equal (for no gap) or if you want to have 20px distance between them just set seriesBarDistance to 50 (30 from stroke-width + 20px gap). Im new to Chartist and I do not know how you structured your data, so I might be wrong (if so, please correct me).

![screenshot 2016-07-28 10 53 04](https://cloud.githubusercontent.com/assets/6840850/17206748/94c125e6-54b1-11e6-92f1-923b257b54d5.png)

**Comment by Zaid-Mirza** [comment]
`var data = {
             labels: myVictimlabels,
             series: myVictimseries
         };
         var barchart = new Chartist.Bar('#barchart', data, { distributeSeries: true}, {

```
         seriesBarDistance:100,
         axisX: {
             // On the x-axis start means top and end means bottom
             position: 'start'
         },
         axisY: {
             // On the y-axis start means left and end means right
             position: 'start',
             onlyInteger: true,



         }
     });`
```

I have tried this serieesBarDistance:50 and 100 also but not result. my data is simple but contains in arrays.

**Comment by Zaid-Mirza** [comment]
sorry for late reply I was off

**Comment by Zaid-Mirza** [comment]
@metodribic seriesBarDistance works between bars in single bar group. I tested it in examples

**Comment by gionkunz** [comment]
seriesBarDistance does not work for distributed series. You should style your bar width with CSS and responsive breakpoints if you're covering different media.

**Comment by felixxuoptovistech** [comment]
The same issue as above
