### ISSUE TITLE
Dynamic Line Chart not rendering properly

### ISSUE THREAD

**Issue by jeremyfry** [chartist-js/chartist#754]
I have a Line chart that I'm dynamically adding values to. It starts with a few value in the series:
`this.dataSets = { series: [[1,2,3,4,5,6,7], [1,2,3]] };`

And then at a regular interval I add values to the line graph and call the update function:

```
this.dataSets.series[dataIndex].push(+dataItem.SensorValue);
this.chart.update();
```

The amount of x-axis sections does not get updated to the new value of items in the series. Instead it stays at a value equal to the number of items in the largest initial series (in this example, 3). 
![overflow](https://cloud.githubusercontent.com/assets/316541/17466273/28f16002-5cda-11e6-8669-eaddb43d37ff.jpg)

Any thoughts on how I could fix this?

**Comment by jeremyfry** [comment]
Not a fix, but a temporary work around I found. Updating the value of the labels before each update causes the graph resize properly. I'm not actually setting any labels but putting in `this.dataSets.labels = null` before each update cause the redraw to work properly.

**Comment by gionkunz** [comment]
Hi there. Thanks for the report! This is a mutable data issue. Chartist is normalizing the data you're passing to it when constructing a new chart. https://github.com/gionkunz/chartist-js/blob/develop/src/scripts/core.js#L334-L365 These operations are performed directly on the data object you're passing in. So the second time your using the same data object to update Chartist, it has already updated the labels in your object within the normalization. This also explains that the normalization is reapplied if youre setting the labels again to `null`.

I'd like to avoid handling mutable data issues in Chartist, since it would mean we need to make a deep copy of the whole data structure which could lead to performance issues.

I see two possible solutions:

1) You're passing a new data object when you're performing your updates:

``` javascript
this.chart.update({series: this.dataSeries.series});
```

2) We change the code in the core to always check if the labels array contains less labels than the max data series and then apply padding with empty labels. At the moment we only check if we need to fill the labels array, if the labels array is not defined or it's length is 0

**Comment by gionkunz** [comment]
I've marked this as a bug because its confusing behaviour

**Comment by gionkunz** [comment]
I have the feeling we should go with 2 since this is the only option which can prevent confusion in the future
