### ISSUE TITLE
Question: Full width line with two values independently of number of label values 

### ISSUE THREAD

**Issue by metodribic** [chartist-js/chartist#756]
Is there a way to create line with only two values which would take full width no matter how many points does AxisX has ? I found a way with null values and lineSmooth as shown below but I was wondering if there is cleaner solution without null values ?

```
new Chartist.Line('.ct-chart', {
  labels: [1, 2, 3, 4, 5, 6, 7, 8],
  series: [
    [2, null, null, null, null, null, null, null, 7]
  ]
}, {
  low: 0,
  lineSmooth: Chartist.Interpolation.none({
        fillHoles: true
      })
});
```

Working example: [JSbin](http://jsbin.com/zojozedize/edit?html,js,output)

**Comment by gionkunz** [comment]
Hi there. Since the Chartist default axis type is a step based axis, you'll need to fill the missing data with null or undefined.

However, you can also use the fixed scale axis (which comes with it's own caveats) to achieve this: http://jsbin.com/mifubef/1/edit?js,output

The `FixedScaleAxis` allows you to draw any kind of graph and relies on x / y data to project the graph. There is some explanation on our doc site around custom axis: http://gionkunz.github.io/chartist-js/getting-started.html#switching-axis-type

Hope this helps.
Cheers

**Comment by metodribic** [comment]
Thank you very much for your answer, it helps a lot! :)
