### ISSUE TITLE
Lables for x and y axis

### ISSUE THREAD

**Issue by eamonyates** [chartist-js/chartist#817]
Hi,

I have been struggling to find an answer to this but is it possible to have custom labels for both the x and y axis of a graph?

Thanks,
Eamon

**Comment by eamonyates** [comment]
To update,

I have tried using the following code:

```
var data = {
    labels: ['week 1', 'week 2', 'week 3']
    series: [1, 2, 3, 4, 5]
};

var options = {
    distributeSeries: true,
    chartPadding:30,
    axisY: {
        type: Chartist.StepAxis,
        ticks: ['', 'one', 'two', 'three', 'four', 'five'],
        stretch:true
    }
};

new Chartist.Bar('.ct-chart', data, options);
```

This produces a label on the yAxis but the bar chart doesnt populate properly. The bars simply fill right to the top of the chart rather than at the correct series points. If I remove `distributeSeries:true` then the bar chart doesn't populate at all with any data.

Is this the right way to be doing this or is there a better way?

Thanks,
Eamon

**Comment by gionkunz** [comment]
Can you step back and explain what you'd like to visualize? I see 5 series but only 3 labels. In `distributeSeries` mode you're passing a one dimensional array and each value represents a series. This is used if you'd like to show a momentum bar chart and not series over time. If you'd like to show series over time you'd need to do something like the example below. But then your X axis ticks (labels) need to be the same count as your series.

You can use label interpolation to translate your Y values. Using ticks on an axis is a nice finding, but ticks are generally expected to be of numeric value because they get used to project the values on the axis. Only the step axis does not require numeric ticks, since it will use the index to project (step by step).

Here's the example, hope it works out for you: http://jsbin.com/wujubem/edit?html,js,output

**Comment by gionkunz** [comment]
BTW, I started to post this default reply on general questions: 
Please use http://stackoverflow.com/ for these kind of questions, we should only track bugs, feature requests or questions on internals within this Github repository.

**Comment by eamonyates** [comment]
Thanks Gion,

Using label interpolation was exactly what I was looking for. Sorry for putting the question in the wrong place and thank you for the quick response. It worked! 

Kind Regards,
Eamon
