### ISSUE TITLE
Reverse the order of ct-labels and ct-series group

### ISSUE THREAD

**Issue by samageloff** [chartist-js/chartist#820]
![pasted_image_10_27_16__3_12_pm](https://cloud.githubusercontent.com/assets/843090/19782347/7eb2cd12-9c5b-11e6-9bf7-7354c71fe520.png)

^ is this possible?

We've created a tooltip that has a "hit-state" (full height of chart), and the ordering of the SVG DOM inhibits hovering over the left-hand side of the chart in our case. 

![pasted_image_10_27_16__5_21_pm](https://cloud.githubusercontent.com/assets/843090/19786627/e89e3296-9c6c-11e6-8aea-ee8ae5f0cc27.png)

Any help here is appreciated!

**Comment by jivinivan** [comment]
I'm interested in this as well.

**Comment by Arantiryo** [comment]
Hello @samageloff 👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).

Please let me know if the issue is still relevant to you so we can further look into it!
