### ISSUE TITLE
Pie Chart hide some labels using labelInterpolationFnc

### ISSUE THREAD

**Issue by arashkay** [chartist-js/chartist#823]
Hi,

Is there a way to hide some labels on pie charts?

I have labels overlapping on each other and trying to use labelInterpolationFnc and hide some labels based on their % but I don't have access to the original dataset to do the calculation.

Thanks

**Comment by Arantiryo** [comment]
Hello @arashkay 👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).

Please let me know if the issue is still relevant to you so we can further look into it!
