### ISSUE TITLE
Pie chart alignment

### ISSUE THREAD

**Issue by Webbrother** [chartist-js/chartist#825]
Hello.
Is there any way to align pie chart inside svg box in a specific direction? I mean something like in CSS ( for example some options property like {align: 'right'} )?
If no, any ideas on how I can implement it? Thank you.

**Comment by Arantiryo** [comment]
Hello @Webbrother 👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).

Please let me know if the issue is still relevant to you so we can further look into it!
