### ISSUE TITLE
display large number of data on x-axis

### ISSUE THREAD

**Issue by dishantarora** [chartist-js/chartist#849]
Hi, I am using Chartist.js and it is working very good at my end but I am facing one issue which I was not able to resolve.

ISSUE: I want to plot a timeseries data from a date to current date at interval of one week. In my chart the x axis labels are overlapping as the number of points are large, Is there any way to display such large number of data clearly.

![untitled](https://cloud.githubusercontent.com/assets/10178544/20876187/3144d710-bae6-11e6-8ad6-8e30f9322a77.png)

![untitled](https://cloud.githubusercontent.com/assets/10178544/20876204/49abd966-bae6-11e6-86d5-3f2e877a8527.png)

**Comment by metodribic** [comment]
I believe you could either simplify your labels to be shorter or you could rotate labels horizontally like mentioned here [#375](https://github.com/gionkunz/chartist-js/issues/375). Eventually you could show only every second or third (or maybe event every seventh - every week start) label with draw event.

**Comment by dishantarora** [comment]
Is there a way of creating slider for x-axis or has anybody done that before. I am trying to get it done by myself, It would be great if it already exist. Slider will solve my problem.

**Comment by metodribic** [comment]
I'm not sure what kind of slider do you have in mind, but simple CSS propery 
```css
overflow: scroll 
```
could do the trick. Check my [JsBin](http://jsbin.com/gosimiweya/1/edit?html,css,js,output) if this is what you had in mind. (also side note: overflow scroll bars are hidden on mac by default, just hover the chart and try to scroll it horizontally).

**Comment by jacobq** [comment]
If I understand correctly, the heart of this issue is that in many cases the horizontal axis represents a continuous range of data. It is not simply that there are many data points but rather that it is not desirable to label the horizontal value of each point along the axis. For example, here is a typical scatter plot generated by Excel illustrating why this feature is desired:
![temp-chart](https://cloud.githubusercontent.com/assets/1633459/21939000/5ee8b270-d983-11e6-876e-ff3c2f480b0e.png)
In my case, I want the x axis tick marks and labels to be independent of the source data since they are separate concerns (content vs. presentation). A solution that I've seen in other charting software is to differentiate between "line" and "scatter" charts, where the former functions almost identically to a bar chart: it has a sequential "category" axis that is not necessarily quantitative. On the other hand, the latter has a quantitative, i.e. "value", axis along which the data is plotted according to some scale (linear, logarithmic, etc.). For a casual user, these look and feel very similar, but they are subtly different (and a data scientist or data visualization enthusiast would probably make a big deal of it). To illustrate this difference, consider a simple data set that does not have uniform horizontal steps. The 3 charts below all show exactly the same input data:
![temp-chart-types](https://cloud.githubusercontent.com/assets/1633459/21939383/2fe254b6-d985-11e6-9dd5-ab01e4375e9f.png)

Note also that regardless of whether a line or scatter plot is used, it is desirable to be able to control how the axis values are labeled. For example, here is a line chart where each horizontal step represents 1 month, each tick mark represents 3 months, and labels are spaced at intervals of 12 months:
![temp-line-labels](https://cloud.githubusercontent.com/assets/1633459/21940256/1e9a8f6c-d989-11e6-877c-432b79df3c72.png)


See also:
[Line Graph](http://datavizcatalogue.com/methods/line_graph.html)
[Scatterplot](http://datavizcatalogue.com/methods/scatterplot.html)

**Comment by jacobq** [comment]
Also, there is an example on the documentation site that shows a way to reduce the number of data labels [using `options.axisX.labelInterpolationFnc`](https://gionkunz.github.io/chartist-js/examples.html#line-scatter-random) that may help solve the original problem as metodribic suggested above.

**Comment by mwri** [comment]
I encountered this too, the HTML and code below shows much the same problem. You can fix it by setting scaleMinSpace, but of course it's tricky because the value you need depends on the data; 20 works for the below, but increase the x values by a couple of orders of magnitude and you need it to be 30+.

    <div class="ct-chart ct-major-tenth"></div>
    <script type="text/javascript">
    var data = { series: [[{x: 100, y: 0.2}, {x: 10000, y: 0.26}, {x: 20000, y: 0.25}, {x: 100000, y: 0.29}, {x: 5000000, y: 0.37}]] };
    new Chartist.Line('.ct-chart', data, { axisX: { type: Chartist.AutoScaleAxis } });
    </script>

**Comment by waterazu** [comment]
Hi there,
I have a Line chart where I'm trying to paint 800 points in the x-axis.
Is there a way with AutoScaleAxis, FixedScaleAxis or StepAxis, to automatically reduce the number of points to for example 300 and do you know how to achieve that, is possible?

I've played with them but I don't manage to do it.

Thanks

**Comment by duchuy** [comment]
`Option:

axisX: {

          labelInterpolationFnc: function (value, index) {        
         
                  return index % 10 == 0 ? value: null;
          }

        },`

**Comment by aakashsigdel** [comment]
@jacobq  I think @dishantarora  is looking for something like this.
https://jsfiddle.net/alidingling/mc8r7e6p/

Recharts has `<Brush />` component for this. It would be awesome to have it here as well.

**Comment by viswanathmantri** [comment]
Hi my Chartist number of curves is limited to 3 curves, How can i increase it to n number of curves in a Graph Chart
