### ISSUE TITLE
Seperate library code from website

### ISSUE THREAD

**Issue by autarc** [chartist-js/chartist#88]
As Chartist itself is a library and not a service, its confusing to keep the static files for the website documentation along with the JavaScript sources. Since github pages are already used a clean seperation should be reasonable. Plain examples how to use certain features could still be shown in a 'examples' folder. This would also allows to use common terms for the existing structure (e.g. "libdist" was probably choosen instead of "dist" to provide a hint that its the code and not the website build).

**Comment by gionkunz** [comment]
Hi there. The reason why we still stick to this is mainly because Chartist is a very visual library and it's very nice to develop on the library while using the documentation site as a fast feedback for your development changes. If we rip out the documentation site into its own project we'd need to have a way how to develop on Chartist and have a visual representation / sandbox in order to develop more rapidly. Actually I see the point to separate the library from the site, but I do like the benefit of having a living sandbox during development. Also I like the fact the for contributors they only need to grab one repository and they can hack around. 

What if we stick to this but make the separation even more clear? I.E. Also put images, scripts/site and styles/site into site/images, site/scripts and site/styles ?

**Comment by autarc** [comment]
Thats seems to be the dilema of larger libraries and frameworks in general, often handled with a seperate repository just containing the static website. I think we can avoid this overhead by making the seperation more clear as you mentioned. Extracting the `website` specific code for the documentation and also provide `examples` on how to use the library would definately help. [Chart.js](https://github.com/nnnick/Chart.js) has a similar approach, which makes it easy for others to take a look at the source or specific use cases.
