### ISSUE TITLE
Error: <path> attribute d: Expected number, "MNaN,459.375CNaN,…".

### ISSUE THREAD

**Issue by paulMD1** [chartist-js/chartist#888]
Hi,
I found another thread with the same error:
https://github.com/gionkunz/chartist-js/issues/822

unfortunately, was not able to figure out why my line chart would have the same error. Here is an example code.

Thank you,
Paul

 <html>
  <head>
    <script type="text/javascript" src="C:\JSLib\chartist-js-develop\dist\Chartist.js"></script>
 
  </head>
  <body>
    <div class="curve_chart" style="width: 900px; height: 500px"></div>
	
	   <script type="text/javascript">
       
	  
      function drawChart() {
		var jsonTxt = '{"perHit":[60,70,80,75],"date":["2014-12-3","2015-12-4","2016-4-6","2016-12-5"]}';
			
		var jsonData = JSON.parse(jsonTxt);
		jsonData.newDate = [];
		var pingChartData = {
			labels: [],
			series: [new Array]
		}
		pingChartData.series[0].push(1);
		pingChartData.labels.push(Date(1));
		pingChart = new Chartist.Line('.curve_chart', pingChartData, {
			fullWidth: true,
			axisX: {
				type: Chartist.AutoScaleAxis,
			},
			axisY: {
				showGrid: false,
			},
			lineSmooth: Chartist.Interpolation.simple(),
			showArea: true,
			showPoint: false,
		})

		
		for(var i= 0; i<jsonData.date.length;i++)
		{
			jsonData.newDate[i] = new Date (jsonData.date[i]);
			pingChartData.labels.push(jsonData.newDate[i].toDateString());
			pingChartData.series[0].push(jsonData.perHit[i]);
			

		}
		pingChart.update(pingChartData);
		

      }
	  
	  drawChart();
    </script>
	
  </body>
</html>

**Comment by sbaechler** [comment]
I have the same error. The error only happens if you set type to FixedScaleAxis or AutoScaleAxis.

The error happens when Chartist tries to draw the line and enters the function `attr(attributes, ns)`. 
The attribute is `d` and the value is an array that contains NaNs: "MNaN,15LNaN,15LNa…".
Labels and series are `[1, 2, 3, 4]`.

**Comment by sbaechler** [comment]
The error doesn't happen if I use object for the series entries instead of labels.

**Comment by gionkunz** [comment]
Few things to watch out for:

- When specifying an axis type you need to switch to multi dimensional values ({x: 0, y: 0}) as you can also see from the examples here http://gionkunz.github.io/chartist-js/getting-started.html#switching-axis-type
- When specifying an axis type, the according value on the axis will be used as a label and also to compute the projection. You need to pass numeric values. In your example you can pass a Date object since it can be converted to a number (timestamp) and therefore does work with the projection math. Since you don't want to render timestamps as labels, you can use labelInterpolationFnc to format using Intl or Moment.js

Here's your working example:
```javascript
function drawChart() {
	var jsonTxt = '{"perHit":[60,70,80,75],"date":["2014-12-3","2015-12-4","2016-4-6","2016-12-5"]}';
		
	var jsonData = JSON.parse(jsonTxt);

	pingChart = new Chartist.Line('.curve_chart', null, {
		axisX: {
			type: Chartist.AutoScaleAxis,
      labelInterpolationFnc: function(value) {
        return new Intl.DateTimeFormat().format(value);
      },
      scaleMinSpace: 50
		},
		axisY: {
			showGrid: false,
		},
		lineSmooth: Chartist.Interpolation.simple(),
		showArea: true,
		showPoint: false,
	})

	
	pingChart.update({
    series: [
      jsonData.perHit.map(function(hit, index) {
        return {
          x: new Date(jsonData.date[index]),
          y: hit
        }
      })
    ]
  });

}
  
drawChart();
```
