### ISSUE TITLE
Is this project live?

### ISSUE THREAD

**Issue by luisfmsouza** [chartist-js/chartist#907]
I was looking to the [last month pulse chart](https://github.com/gionkunz/chartist-js/pulse/monthly), and I notice the activity is not so intense.

Also, there's no merged Pull Requests since November.

So... is this project live?

**Comment by gionkunz** [comment]
Hi @luisfmsouza , Yes this project is alive. I'm currently working on the 1.0 release which will be a partial rebuild of the library. Chartist 0.x will soon switch into maintenance mode and we will only fix critical bugs on the 0.x branch. Since this is an open source project, you could also start contributing if you think the activity on the project is not intense enough :-)

**Comment by luisfmsouza** [comment]
Nice @gionkunz. I didn't see any information about the 1.0 release and the repo, where it is?

Also, I was afraid to contribute because the PRs are not being merged. Did you stop merging PRs because of 1.0 release?
