### ISSUE TITLE
Option to make graph smoothing less agressive

### ISSUE THREAD

**Issue by danieldiekmeier** [chartist-js/chartist#92]
Hey,

I love Chartist and use it on my reading platform [Lesetagebuch](https://lesetagebu.ch/) to show statistics about the finished books and pages per month. But if somebody didn't read something in one of the months, the graph falls beneath the 0-line. That's not really what I want.

![screen shot 2014-11-26 at 13 34 46](https://cloud.githubusercontent.com/assets/2098462/5201353/04269708-7571-11e4-81a1-aa5452d42d0b.png)

Is there a possibility of toning this down a bit?

Regards,
Daniel

**Comment by gionkunz** [comment]
Salü Daniel :-) Thanks for the kind words. Chartist.js currently uses a interpolation technique called catmull rom spline. It's very accurate when it comes to approximation to the data points, however, it can create some artifacts when there are big jumps in the data. I think it would be nice to add other interpolation algorithms like https://en.wikipedia.org/wiki/Cubic_Hermite_spline#Cardinal_spline which are accurate too but create less or different artifacts. There is a lot on our plate currently and we are missing some contribution so unless we can find someone who is taking care of this, I think it would take some time until I can pick this up. In the meanwhile the only thing that comes to my mind is working around this issue by either disabling line smoothing for your line chart or by configuring a low that is below your lowest data point so that the artifacts from catmoll rom is not overflowing.

Besides your issue, may I ask you how you achieve to render a Bar chart on top of your Line chart? :-) Do you create a second chart in the same container and disable grid and labels?

**Comment by danieldiekmeier** [comment]
Hey Gion, I just had a look into the source code, so maybe I'll add some more smoothing methods myself, if I find the time. (But as I have an acute interest in this, that may _actually_ happen.)

Yes, I'm just rendering two charts, and disable everything except the chart and its y-labels on the second one. I'm also translating the line chart by half a step so it overlaps on the right spots. You can have a look into the dev tools, if you want: https://lesetagebu.ch/von/danjel

**Comment by gionkunz** [comment]
Cool :-) We are also working on a compound chart type #37 but I guess that's a nice workaround :-)

**Comment by maslowivan** [comment]
:+1:  waiting for fixed

**Comment by gionkunz** [comment]
@danieldiekmeier , the base is now there to implement more smoothing / interpolation functions. You can model your interpolation function after this one: https://github.com/gionkunz/chartist-js/blob/develop/src/scripts/interpolation.js#L30-L103 and also put it into the interpolation module / expose it there. This is a first draft of how we offer this API. Please provide feedback if you find any flaws. Also I recognize a conflict between simple naming with `lineSmooth` vs. the fact that you could also do other things than smoothing in an interpolation. But for the sake of backwards compatibility let's keep it like this. The logic how the `lineSmooth` option is handles is here: https://github.com/gionkunz/chartist-js/blob/develop/src/scripts/charts/line.js#L222-L224

**Comment by gionkunz** [comment]
Usage example can be found here: https://github.com/gionkunz/chartist-js/blob/develop/src/scripts/charts/line.js#L320-L332

**Comment by gionkunz** [comment]
The function returned by the factory function accepts all path coordinates [x, y, x, y, x, y, .....] and should return a SVG path object: http://gionkunz.github.io/chartist-js/api-documentation.html#module-chartistsvgpath

Tell me that you think!

**Comment by aacook** [comment]
Is there any way to just disable smoothing completely? For certain situations I find the smoothing hard to read. (e.g. trying to study daily totals for things)

**Comment by leeoniya** [comment]
@aacook 

http://gionkunz.github.io/chartist-js/api-documentation.html#chartistinterpolation-method-none

or

https://github.com/gionkunz/chartist-js/blob/673c45393e05cf6dd3bf2393c3a213c65abdaca8/site/examples/example-plugin-accessibility.js#L9
