### ISSUE TITLE
CDN link example broken in "USE A CDN ALTERNATIVELY" 

### ISSUE THREAD

**Issue by camillo777** [chartist-js/chartist#931]
Hi just to let you know that the CDN import example in the getting started section of the web site has broken links:

href="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.css"

src="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"

Both are missing the "http:". 

Maybe this is known, but after making copy paste of the example I spent some time thinking nothing was working just because of this. 

All best, 
Camillo

**Comment by gionkunz** [comment]
Hi @camillo777 

// is a valid protocol relative URL, see http://blog.httpwatch.com/2010/02/10/using-protocol-relative-urls-to-switch-between-http-and-https/

This is usefull because it does not tie you to either HTTP or HTTPS but will choose the right protocol given the current origin protocol.

If you're serving from file:// (which you should try to avoid anyway) this wont work I believe.

**Comment by camillo777** [comment]
Hi! Cool, I did not know that!
But it is strange because with Chrome on Android it does not seem to work.
Maybe it is a platform limitation?
Thank you!
Camillo

2017-04-10 16:42 GMT+02:00 Gion Kunz <notifications@github.com>:

**Comment by lousongtao** [comment]
this problem also bother me long time until I read this issue. I use firefox and Chrome. Without the HTTP, both web browsers cannot load the js and css. I don't know why other people not report this issue?
