### ISSUE TITLE
Plotting series of different sizes on a Line Chart 

### ISSUE THREAD

**Issue by GabrielSiq** [chartist-js/chartist#939]
Hi, 

First of all, thank you for your work on Chartist. 

I've recently come across the following problem: I've been using Chartist to make line charts in my application. Those charts usually have more than one series and these series are sometimes of different sizes. What I'd like to do is to merge all labels in one list (no duplicates) and plot two or more series that might not have data points for every label. The easy solution for that would be to fill the series with zeros where there isn't a data point so every series would have the same size,  but that won't look very good. Is there any way to accomplish what I'm trying? Thanks!

**Comment by gionkunz** [comment]
Hi there

Did you look at the holes in data example? http://gionkunz.github.io/chartist-js/examples.html#example-line-data-holes

**Comment by GabrielSiq** [comment]
Hello,

No, I didn't. Sorry for having missed that, that's exactly what I needed! Now, looking at that example, I understood the first 3 series which have null in the series for the points of x where there isn't a data point. However, I didn't get the last one.

[{x:3, y: 3},{x: 4, y: 3}, {x: 5, y: undefined}, {x: 6, y: 4}, {x: 7, y: null}, {x: 8, y: 4}, {x: 9, y: 4}]

At first I thought it described the individual data points but there isn't anything plotted at {x:3, y:3} for example.

I really appreciate your help - it solved my problem - but could you point me towards the part of the documentation that explains this behavior?

**Comment by gionkunz** [comment]
The example is misleading. The problem is that within a standard axis configuration on line charts, the X value is getting ignored. That is because the standard X axis is a `StepAxis` which does not use the value but the index to plot each data point one after each other. If you'd switch the X axis to `AutoScaleAxis` or `FixedScaleAxis` you'd notice the difference. Check this guide if you want to know how to switch axis: https://gionkunz.github.io/chartist-js/getting-started.html#switching-axis-type

Here's a simple example:

```javascript
var chart = new Chartist.Line('.ct-chart', {
  labels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
  series: [
    [{x:3, y: 3},{x: 4, y: 3}, {x: 5, y: undefined}, {x: 6, y: 4}, {x: 7, y: null}, {x: 8, y: 4}, {x: 9, y: 4}]
  ]
}, {
  fullWidth: true,
  chartPadding: {
    right: 10
  },
  low: 0,
  axisX: {
    type: Chartist.AutoScaleAxis,
    onlyInteger: true
  }
});
```

**Comment by GabrielSiq** [comment]
Thanks, it makes sense and I've been able to use it correctly.

As a last question - and sorry if this isn't the right place for those - I'm using Chartist to render a line chart to which I add and remove series via javascript + `.update()`. Now, when removing a series, all series that come after it change colors - I assume to follow the default color scheme. The next series takes on the color of the series that was deleted and so on. Is there an easy way for me to keep the colors as I dynamically add/remove series from my data and update the chart?

**Comment by gionkunz** [comment]
With a standard setup, the order and amount of series dictate their series name. Let's say you have 3 series. Series-a, series-b and series-c. If you now remove the second series, then your previous 3rd series will become the second one, since that is the new order.

In situations like this I recommend you to use the series object notation and specify your series class names in your data:

```javascript
new Chartist.Line('.ct-chart', {
  labels: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
  series: [{
    data: [12, 9, 7, 8, 5],
    className: 'ct-series-a'
  }, {
    data: [2, 1, 3.5, 7, 3],
    className: 'ct-series-c'
  }, {
    data: [1, 3, 4, 5, 6],
    className: 'ct-series-b'
  }]
}, {
  fullWidth: true,
  chartPadding: {
    right: 40
  }
});
```

This way you're not depending on the order of your series and you can remove / add more series dynamically.

**Comment by GabrielSiq** [comment]
Perfect, thanks!
