### ISSUE TITLE
Pie chart series name class for text ct-label element

### ISSUE THREAD

**Issue by karinseve** [chartist-js/chartist#942]
I'm using a donut chart [like in the examples](https://gionkunz.github.io/chartist-js/examples.html#example-donut-solid-chart): 
The produced HTML code (FRAGMENT) is 

```
<g>
<text dx="134.29110117477677" 
      dy="30.08812886535611" 
      text-anchor="middle" class="ct-label">3400
      </text>
<text dx="143.04223215855663" 
        dy="247.2452044679772" 
        text-anchor="middle" class="ct-label">1800
        </text>
</g>
```
As you can see I'm not able to customize with CSS the two labels differently, because they have the same class. Even if I set up 

 ```
series: [{
    value: 20,
    name: 'Series 1',
    className: 'my-custom-class-one',
    meta: 'Meta One'
  }
```
I would expect to obtain 

```
<g>
<text dx="134.29110117477677" 
      dy="30.08812886535611" 
      text-anchor="middle" class="ct-label my-custom-class-one">20
      </text>
...
</g>
```

**Comment by gionkunz** [comment]
That's a bit unfortunate at the moment, but is not likely to change before the Major update with 1.0.0. You can use an ugly selector approach as a workaround. .ct-label:nth-child(1), .ct-label:nth-child(2) etc.

**Comment by karinseve** [comment]
I see, would you consider a pull request?

**Comment by petervtzand** [comment]
@gionkunz I have the same problem. Your suggested solution fixes it, unless you have a 0 value (for example `[0, 6, 7]`, and `ignoreEmptyValues: true`.  When this is the case, In `series-b` `.ct-label:nth-child(1)` and in `series-c` `.ct-label:nth-child(2)` are shown (instead of label 2 & 3)

To fix this problem I set `ignoreEmptyValues: false` and created a `labelInterpolationFnc` that returns `' '` if value === 0, but that is very hacky.

My suggested solution is that the className of the 'slice', like 'series-a' or 'my-custom-class-name' is set on the label as well.  I created a PR for it: https://github.com/gionkunz/chartist-js/pull/1198
