### ISSUE TITLE
chartist.FixedScaleAxis: on resize values get sorted magically

### ISSUE THREAD

**Issue by camillo777** [chartist-js/chartist#965]
I have got this simple chart; adding this configuration to Y axis:

```
type: chartist.FixedScaleAxis,
ticks: values,
low: 0

```

When I resize window where is chart, chart is redrawn with values with different sorting than original:

```
new chartist.Bar(
    '.ct-chart',
    { labels: labels,
      series: [values]},
      {
        axisX: {
          onlyInteger: true
        },
         axisY: {
           onlyInteger: true,
           type: chartist.FixedScaleAxis,
           ticks: values,
           low: 0
         },
         lineSmooth: chartist.Interpolation.step()
      }
    );
```

See the screenshots attached, before resize and after some pixels resize.

**Before resize:**
<img width="779" alt="screen shot 2017-06-11 at 21 07 09" src="https://user-images.githubusercontent.com/4798456/27013732-1b32e758-4eea-11e7-886d-4d4c135f4f0f.png">

**After resize:**
<img width="761" alt="screen shot 2017-06-11 at 21 07 17" src="https://user-images.githubusercontent.com/4798456/27013733-1b3435ea-4eea-11e7-878f-9c0c517dbfaa.png">

**Comment by Arantiryo** [comment]
Hello @camillo777 👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).

Please let me know if the issue is still relevant to you so we can further look into it!
