### ISSUE TITLE
Trying to run an example

### ISSUE THREAD

**Issue by ArthurZ** [chartist-js/chartist#97]
Hi,
I am trying to run my 1st example using Chartist based on http://gionkunz.github.io/chartist-js/getting-started.html
But getting an error:
ReferenceError: Chartist is not defined. 
It is from FireFox (dev tool)
My code snippet is at https://gist.github.com/ArthurZ/b133179a28814321970d 
What could go wrong?

**Comment by cybrox** [comment]
You're not actually embedding the Chartist javascript and css files.
If you want to use the CDN, don't forget to add `https:` in front of the link you currently embed, otherwise your browser will attempt to load a local file. 

Change line 4 and 5 to:

```
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/chartist.js/latest/chartist.min.css">
  <script src="https://cdn.jsdelivr.net/chartist.js/latest/chartist.min.js">
```

Also, you might want to include your script **after** your container or add a document ready event to make sure that the container exists before trying to access it.
/edit: Whoops, didn't notice that @gionkunz already commented on the gist.

**Comment by ArthurZ** [comment]
Thank you cybrox and gionkunz, yes, adding the https and repositioning the JavaScript code into the bottom of the body has fixed the issue.
