### ISSUE TITLE
Multiple Charts with VAR data included

### ISSUE THREAD

**Issue by mikeisrain** [chartist-js/chartist#980]
First off, absolutely loving chartist. Had to get that off my chest. ;)

So, here is my issue, I am trying to throw a few different charts onto a page, and I know I can, using the example on the getting started page, put ID's to the respective charts and in the scripts.

However, I am not successfully able to add multiple charts that also include data, options, etc.

Below is my code that works with the example ID, and I cannot for the life figure out how to give each chart a proper unique ID, without receiving a script error in the 2nd example.

`new Chartist.Line('#chart1', {
		  labels: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
		  series: [
			[12, 9, 7, 8, 5],
			[2, 1, 3.5, 7, 3],
			[1, 3, 4, 5, 6]
		  ]
		}, {
		  fullWidth: true,
		  chartPadding: {
			right: 40
  }
});`

Where in the script do I place my ID, into the script fucntion?

`var data = {
  labels: ['Jan', 'Feb', 'Mar', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    series: [
    [5, 4, 3, 7, 5, 10, 3, 4, 8, 10, 6, 8],
    [3, 2, 9, 5, 4, 6, 4, 6, 7, 8, 7, 4]
  ]
};

var options = {
  seriesBarDistance: 15
};

var responsiveOptions = [
  ['screen and (min-width: 641px) and (max-width: 1024px)', {
    seriesBarDistance: 10,
    axisX: {
      labelInterpolationFnc: function (value) {
        return value;
      }
    }
  }],
  ['screen and (max-width: 640px)', {
    seriesBarDistance: 5,
    axisX: {
      labelInterpolationFnc: function (value) {
        return value[0];
      }
    }
  }]
];

new Chartist.Bar('.ct-chart', data, options, responsiveOptions);`

Any help would be VERY much appreciated. I know it's probably a very simple addition to the code, but I have tried many things and I guess my js is lacking.

Thanks!
Mike

**Comment by wdemars** [comment]
@mikeisrain, without seeing your html markup, let me point you to a couple of items that you can review: 

- the '#chart1' in the first example selects a specific html tag by the ID name, i.e. chart1, so <div id="chart1"></div>
- the '.ct-chart' in the second example is selecting all html tags with the class of 'ct-chart', so if you have the following, the bar chart is overriding your line chart too, since they share the sample class.

<div id='chart1' class='ct-chart'></div>
<div id='chart2' class='ct-chart'></div>

So, the second chart needs to be: new Chartist.Bar('**chart2**', data, options, responsiveOptions);
